smart_home:
  endpoint: https://api.eu.amazonalexa.com/v3/events
  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret
  filter:
    include_entities:
      - binary_sensor.back_door_contact
      - binary_sensor.front_door_contact
      - light.kids_bedroom_switch
      - light.lamp_1
      - light.lamp_2
      - light.lamp_3
      - light.lamp_4
      - light.lamp_5
      - light.lamp_6
      - light.lamp_7
      - light.lamp_8
      - light.master_bedroom_switch
      - media_player.lg_smart_tv
      - sensor.kids_bedroom_climate_temperature
      - sensor.living_room_climate_temperature
      - sensor.lower_floor_climate_temperature
      - sensor.master_bedroom_climate_temperature
      - script.watch_netflix_on_lg_smart_tv
      - script.watch_plex_on_lg_smart_tv
      - script.watch_bbc_iplayer_on_lg_smart_tv
      - script.watch_bbc_one_on_lg_smart_tv
      - script.watch_bbc_news_on_lg_smart_tv
      - script.watch_cbeebies_on_lg_smart_tv
      - script.watch_channel_4_on_lg_smart_tv
      - switch.kids_bedroom_smart_plug
      - switch.living_room_smart_plug
      - switch.lower_floor_smart_plug
      - switch.master_bedroom_smart_plug
      - switch.washing_machine_smart_plug
    exclude_domains:
      - automation
      - binary_sensor
      - button
      - camera
      - device_tracker
      - group
      - input_boolean
      - input_number
      - input_select
      - input_text
      - light
      - media_player
      - number
      - persistent_notification
      - person
      - remote
      - script
      - select
      - sensor
      - sun
      - switch
      - text
      - timer
      - update
      - weather
      - weblink
      - zone
  entity_config:
    media_player.lg_smart_tv:
      name: TV
    script.watch_netflix_on_lg_smart_tv:
      name: Netflix
    script.watch_plex_on_lg_smart_tv:
      name: Plex
    script.watch_bbc_iplayer_on_lg_smart_tv:
      name: BBC iPlayer
    script.watch_bbc_one_on_lg_smart_tv:
      name: BBC One
    script.watch_bbc_news_on_lg_smart_tv:
      name: BBC News
    script.watch_cbeebies_on_lg_smart_tv:
      name: CBeebies
    script.watch_channel_4_on_lg_smart_tv:
      name: Channel 4
    switch.kids_bedroom_smart_plug:
      display_categories: SMARTPLUG
    switch.living_room_smart_plug:
      display_categories: SMARTPLUG
    switch.lower_floor_smart_plug:
      display_categories: SMARTPLUG
    switch.master_bedroom_smart_plug:
      display_categories: SMARTPLUG
    switch.washing_machine_smart_plug:
      display_categories: SMARTPLUG
