- alias: Sensor low battery, send notification
  id: 18fc67d1-97f9-4d81-93bc-71bf0c47a05e
  mode: queued
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.back_door_battery
        - sensor.front_door_battery
        - sensor.front_door_mailbox_battery
        - sensor.kids_bedroom_climate_battery
        - sensor.kids_corner_switch_battery
        - sensor.laundry_room_climate_battery
        - sensor.living_room_climate_battery
        - sensor.lower_floor_climate_battery
        - sensor.master_bedroom_climate_battery
        - sensor.smart_switch_battery
        - sensor.smart_vibration_sensor_battery
      below: 15
  action:
    - service: persistent_notification.create
      data:
        title: "Device with low battery"
        message: "The {{ trigger.to_state.attributes.friendly_name }} sensor has low battery!"
        notification_id: "{{ trigger.entity_id }}-battery"

- alias: Set device connectivity state
  id: 04401784-2ac3-408d-a75e-4edd6e2c24cb
  use_blueprint:
    path: device_connectivity_state.yaml
    input:
      on_off_entities:
        - binary_sensor.philips_hue_bridge_2_1
        - binary_sensor.raspberry_pi_2_model_b
        - binary_sensor.synology_ds412_nas
      online_offline_entities:
        - sensor.zigbee2mqtt_bridge_state

- alias: Washing Machine program finished, send notification
  id: c5948e61-ec36-42ef-a057-e9dc0e5c220f
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_program_running
      from: "on"
      to: "off"
  action:
    - service: script.send_notification
      data:
        message: "Washing Machine program finished!"
        channel: "Automation"
        tag: "washingmachine"

- alias: Set door state (Back Door)
  id: 95e1e1a4-85a5-4702-ae25-05186075840c
  use_blueprint:
    path: door_state.yaml
    input:
      door_state_entity: binary_sensor.back_door_contact
      companion_light_entity: light.lamp_3
      light_off_on_door_closed_helper_entity: input_boolean.turn_off_lamp_on_back_door_close

- alias: Set door state (Front Door)
  id: 3f673a0b-8ff1-4fcd-b415-4e4b6d0076eb
  use_blueprint:
    path: door_state.yaml
    input:
      door_state_entity: binary_sensor.front_door_contact
      companion_light_entity: light.lamp_2
      light_off_on_door_closed_helper_entity: input_boolean.turn_off_lamp_on_front_door_close

- alias: Set phone battery state (Pedro)
  id: 3d24676c-7c32-4879-a2c6-5ae513bd4218
  use_blueprint:
    path: phone_battery_state.yaml
    input:
      battery_level_entity: sensor.pedro_oneplus9pro_battery_level
      battery_state_entity: sensor.pedro_oneplus9pro_battery_state
      recipient: pedro

- alias: Set phone battery state (Joana)
  id: 7f291143-de8e-4a29-bcac-5c487dc7457f
  use_blueprint:
    path: phone_battery_state.yaml
    input:
      battery_level_entity: sensor.joana_oneplus9_battery_level
      battery_state_entity: sensor.joana_oneplus9_battery_state
      recipient: joana

- alias: Front Door Mailbox movement, send notification
  id: 5c3f86a6-9406-43fe-a7c3-c8552a69b350
  trigger:
    - platform: state
      entity_id: sensor.front_door_mailbox_action
      to:
        - "drop"
        - "tilt"
        - "vibration"
  condition:
    - "{{ is_state('binary_sensor.front_door_contact', 'off') }}"
  action:
    - service: script.send_notification
      data:
        message: "Movement detected on Front Door Mailbox"
        channel: "Automation"
        tag: "front_door_mailbox"

- alias: Set alarm state
  id: 2d53ff7e-e2b2-40e6-8362-33ede62ae3f6
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
    - platform: time
      at:
        - "01:00:00"
        - "07:00:00"
    - platform: state
      entity_id: group.family
  action:
    choose:
      - conditions:
          - condition: time
            after: "01:00:00"
            before: "07:00:00"
        sequence:
          - service: alarm_control_panel.alarm_arm_night
            entity_id: alarm_control_panel.home_alarm
      - conditions:
          - "{{ not is_state('group.family', 'home') }}"
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            entity_id: alarm_control_panel.home_alarm
    default:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm

- alias: Octoprint print state changed, send notification
  id: 9c2ec395-2c8d-4b4c-bbc1-1af04d38d168
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
  action:
    choose:
      - conditions:
          - "{{ trigger.from_state.state == 'on' and trigger.to_state.state == 'off' }}"
        sequence:
          - service: script.send_notification
            data:
              recipient: "pedro"
              message: "Octoprint done!"
              channel: "Automation"
              tag: "octoprint"
      - conditions:
          - "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: script.clear_notification
            data:
              recipient: "pedro"
              channel: "Automation"
              tag: "octoprint"

- alias: Transmission download complete, send notification
  id: 1091a93a-be80-440b-a61d-ecd27ced6abb
  mode: queued
  trigger:
    - platform: event
      event_type: transmission_downloaded_torrent
  action:
    - service: script.send_notification
      data:
        recipient: "pedro"
        title: "Transmission download complete"
        message: "{{ trigger.event.data.name }}"
        channel: "Automation"
        tag: "transmission"

- alias: Smart Vibration Sensor movement, send notification
  id: 39b75e6e-19c9-4a60-bd72-a7616ed50645
  trigger:
    - platform: state
      entity_id: sensor.smart_vibration_sensor_action
      to:
        - "drop"
        - "tilt"
        - "vibration"
  action:
    - service: script.send_notification_with_lower_floor_camera_snapshot
      data:
        message: "Movement detected on Smart Vibration Sensor"

- alias: Update available, send notification
  id: eafd8f59-39c2-434c-9b29-c1b8be3dfd52
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: "off"
      to: "on"
  action:
    - service: script.send_notification
      data:
        recipient: "pedro"
        message: "Home Assistant update available!"
        channel: "System"
        tag: "homeassistantupdate"

- alias: AdguardHome enabled after 2 minutes
  id: 3ba3ddc1-8f62-4413-9e23-42ae60cc3ba2
  trigger:
    - platform: state
      entity_id: switch.adguard_protection
      to: "off"
      for: "00:02:00"
  action:
    - service: switch.turn_on
      entity_id: switch.adguard_protection

- alias: OBS state changed, set Elgato Key Light Air state
  id: ad07265c-d8aa-441f-9170-b005b1a2e26b
  mode: queued
  trigger:
    - platform: state
      entity_id: switch.obs_virtualcam
  action:
    - service: >-
        {% if trigger.to_state.state == 'on' %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      target:
        entity_id: light.elgato_key_light_air

- alias: Set Zigbee2mqtt log level
  id: 6eb24622-8f61-4a04-bcc4-c24113c2c639
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ trigger.to_state.state }}"
        topic: "zigbee2mqtt/bridge/config/log_level"

- alias: Log Zigbee2mqtt errors
  id: 3f7282b9-5543-47da-966b-0751445c0273
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bridge/log"
  condition:
    - "{{ 'error' in trigger.payload_json.type }}"
  action:
    - service: system_log.write
      data_template:
        message: "{{ trigger.payload_json }}"
        level: warning
