- alias: Sensor low battery, send notification
  id: 18fc67d1-97f9-4d81-93bc-71bf0c47a05e
  mode: queued
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.back_door_battery
        - sensor.front_door_battery
        - sensor.front_door_mailbox_battery
        - sensor.kids_bedroom_climate_battery
        - sensor.kids_corner_switch_battery
        - sensor.laundry_room_climate_battery
        - sensor.living_room_climate_battery
        - sensor.lower_floor_climate_battery
        - sensor.master_bedroom_climate_battery
        - sensor.smart_switch_battery
        - sensor.smart_vibration_sensor_battery
      below: 20
  action:
    - service: persistent_notification.create
      data:
        title: "Device with low battery"
        message: "The {{ trigger.to_state.attributes.friendly_name }} sensor has low battery!"

- alias: Device offline, send notification
  id: 95278467-6b3e-4f4a-a912-10220166dd76
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.philips_hue_bridge_2_1
        - binary_sensor.raspberry_pi_2_model_b
        - binary_sensor.synology_ds412_nas
      to: "off"
      for: "00:01:00"
    - platform: state
      entity_id:
        - sensor.zigbee2mqtt_bridge_state
      to: "offline"
      for: "00:01:00"
  action:
    - service: script.send_notification
      data:
        recipient: "pedro"
        message: "{{ trigger.to_state.attributes.friendly_name }} is offline."
        color: "red"
        channel: "System"
        tag: "{{ trigger.entity_id }}-deviceoffline"

- alias: Device online, clear notification
  id: 69afbe80-e2ab-419e-b0e9-fd230543d25e
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.philips_hue_bridge_2_1
        - binary_sensor.raspberry_pi_2_model_b
        - binary_sensor.synology_ds412_nas
      from: "off"
      to: "on"
    - platform: state
      entity_id:
        - sensor.zigbee2mqtt_bridge_state
      from: "offline"
      to: "online"
  action:
    - service: script.clear_notification
      data:
        recipient: "pedro"
        channel: "System"
        tag: "{{ trigger.entity_id }}-deviceoffline"

- alias: Washing Machine program finished, send notification
  id: c5948e61-ec36-42ef-a057-e9dc0e5c220f
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_program_running
      to: "off"
  action:
    - service: script.send_notification
      data:
        message: "Washing Machine program finished!"
        channel: "Automation"
        tag: "washingmachine"

- alias: Door open, send notification
  id: 65925a44-8500-4e15-a173-a5c8ff1a8cb3
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_contact
        - binary_sensor.front_door_contact
      to: "on"
  action:
    - service: script.send_notification
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} is open!"
        channel: "Alarm"
        tag: "{{ trigger.entity_id }}"

- alias: Door open and lamp off, turn on lamp
  id: ed9a108b-8ec0-4c1e-a4da-cc88092c0941
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_contact
        - binary_sensor.front_door_contact
      to: "on"
  condition:
    - "{{ is_state(trigger.to_state.attributes.lamp_entity_id, 'off') }}"
  action:
    - service: light.turn_on
      data:
        entity_id: "{{ trigger.to_state.attributes.lamp_entity_id }}"
    - service: input_boolean.turn_on
      data:
        entity_id: "{{ trigger.to_state.attributes.lamp_off_entity_id }}"

- alias: Door closed for 30s, turn off lamp
  id: 571fe8c9-bf3b-4711-9f10-9b1c23d4e7ca
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_contact
        - binary_sensor.front_door_contact
      to: "off"
      for: "00:00:30"
  condition:
    - "{{ is_state(trigger.to_state.attributes.lamp_off_entity_id, 'on') }}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: "{{ trigger.to_state.attributes.lamp_off_entity_id }}"
    - service: light.turn_off
      data:
        entity_id: "{{ trigger.to_state.attributes.lamp_entity_id }}"

- alias: Door open for 5 minutes, send notification
  id: 260663cf-9523-406f-9368-6bd35555815f
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_contact
        - binary_sensor.front_door_contact
      to: "on"
      for: "00:05:00"
  action:
    - service: script.send_notification
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} is still open!"
        color: "red"
        channel: "Alarm"
        tag: "{{ trigger.entity_id }}"

- alias: Door closed, send notification
  id: c0da4ec0-91cc-46c2-b21b-2f67d4c9a44e
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_contact
        - binary_sensor.front_door_contact
      to: "off"
  action:
    - service: script.send_notification
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} is closed!"
        channel: "Alarm"
        tag: "{{ trigger.entity_id }}"
        allow_clear: "true"

- alias: Front Door Mailbox movement, send notification
  id: 5c3f86a6-9406-43fe-a7c3-c8552a69b350
  trigger:
    - platform: state
      entity_id: sensor.front_door_mailbox_action
      to:
        - "drop"
        - "tilt"
        - "vibration"
  condition:
    - "{{ is_state('binary_sensor.front_door_contact', 'off') }}"
  action:
    - service: script.send_notification
      data:
        message: "Movement detected on Front Door Mailbox"
        channel: "Automation"
        tag: "front_door_mailbox"

- alias: Set alarm state
  id: 2d53ff7e-e2b2-40e6-8362-33ede62ae3f6
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
    - platform: time
      at:
        - "01:00:00"
        - "07:00:00"
    - platform: state
      entity_id:
        - person.pedro
        - person.joana
  action:
    choose:
      - conditions:
          - condition: time
            after: "01:00:00"
            before: "07:00:00"
        sequence:
          - service: alarm_control_panel.alarm_arm_night
            entity_id: alarm_control_panel.home_alarm
      - conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: group.family
                state: "home"
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            entity_id: alarm_control_panel.home_alarm
    default:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm

- alias: Smart Vibration Sensor movement, send notification
  id: 39b75e6e-19c9-4a60-bd72-a7616ed50645
  trigger:
    - platform: state
      entity_id: sensor.smart_vibration_sensor_action
      to:
        - "drop"
        - "tilt"
        - "vibration"
  action:
    - service: script.send_notification_with_lower_floor_camera_snapshot
      data:
        message: "Movement detected on Smart Vibration Sensor"

- alias: Update available, send notification
  id: eafd8f59-39c2-434c-9b29-c1b8be3dfd52
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: "off"
      to: "on"
  action:
    - service: script.send_notification
      data:
        recipient: "pedro"
        message: "Home Assistant update available!"
        channel: "System"
        tag: "homeassistantupdate"

- alias: AdguardHome enabled after 2 minutes
  id: 3ba3ddc1-8f62-4413-9e23-42ae60cc3ba2
  trigger:
    - platform: state
      entity_id: switch.adguard_protection
      to: "off"
      for: "00:02:00"
  action:
    - service: switch.turn_on
      entity_id: switch.adguard_protection

- alias: Set Zigbee2mqtt log level
  id: 6eb24622-8f61-4a04-bcc4-c24113c2c639
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ trigger.to_state.state }}"
        topic: "zigbee2mqtt/bridge/config/log_level"

- alias: Log Zigbee2mqtt errors
  id: 3f7282b9-5543-47da-966b-0751445c0273
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bridge/log"
  condition:
    - "{{ 'error' in trigger.payload_json.type }}"
  action:
    - service: system_log.write
      data_template:
        message: "{{ trigger.payload_json }}"
        level: warning
