- alias: Device low battery, create persistent notification
  id: 18fc67d1-97f9-4d81-93bc-71bf0c47a05e
  use_blueprint:
    path: device_battery_state.yaml
    input:
      battery_state_entity_id:
        - sensor.back_door_battery
        - sensor.front_door_battery
        - sensor.front_door_mailbox_battery
        - sensor.kids_bedroom_climate_battery
        - sensor.kids_corner_switch_battery
        - sensor.laundry_room_climate_battery
        - sensor.living_room_climate_battery
        - sensor.lower_floor_climate_battery
        - sensor.master_bedroom_climate_battery
        - sensor.smart_switch_battery
        - sensor.smart_vibration_sensor_battery

- alias: Device offline, send notification
  id: 04401784-2ac3-408d-a75e-4edd6e2c24cb
  use_blueprint:
    path: device_connectivity_state.yaml
    input:
      state_entity_id:
        - binary_sensor.raspberry_pi_2_model_b
        - binary_sensor.synology_ds412_nas
        - sensor.zigbee2mqtt_bridge_state

- alias: Washing Machine program finished, send notification
  id: c5948e61-ec36-42ef-a057-e9dc0e5c220f
  triggers:
    - trigger: state
      id: washing_machine_program_finished
      entity_id: binary_sensor.washing_machine_program_running
      from: "on"
      to: "off"
    - trigger: state
      id: washing_machine_program_not_finished
      entity_id: binary_sensor.washing_machine_program_running
      from: "off"
  actions:
    choose:
      - conditions:
          - condition: trigger
            id: washing_machine_program_finished
        sequence:
          - service: script.send_notification
            data:
              message: "Washing Machine program finished!"
              channel: "Automation"
              tag: "washingmachine"
      - conditions:
          - condition: trigger
            id: washing_machine_program_not_finished
        sequence:
          - service: script.clear_notification
            data:
              channel: "Automation"
              tag: "washingmachine"

- alias: Set door state (Back Door)
  id: 95e1e1a4-85a5-4702-ae25-05186075840c
  use_blueprint:
    path: door_state.yaml
    input:
      door_state_entity_id: binary_sensor.back_door_contact
      companion_light_entity_id: light.lamp_3
      light_off_on_door_closed_helper_entity_id: input_boolean.turn_off_lamp_on_back_door_close

- alias: Set door state (Front Door)
  id: 3f673a0b-8ff1-4fcd-b415-4e4b6d0076eb
  use_blueprint:
    path: door_state.yaml
    input:
      door_state_entity_id: binary_sensor.front_door_contact
      companion_light_entity_id: light.kids_corner_group
      light_off_on_door_closed_helper_entity_id: input_boolean.turn_off_lamp_on_front_door_close

- alias: Set phone battery state (Pedro)
  id: 3d24676c-7c32-4879-a2c6-5ae513bd4218
  use_blueprint:
    path: phone_battery_state.yaml
    input:
      battery_level_entity_id: sensor.pedro_pixel9pro_battery_level
      battery_state_entity_id: sensor.pedro_pixel9pro_battery_state
      recipient: pedro

- alias: Set phone battery state (Joana)
  id: 7f291143-de8e-4a29-bcac-5c487dc7457f
  use_blueprint:
    path: phone_battery_state.yaml
    input:
      battery_level_entity_id: sensor.joana_pixel9pro_battery_level
      battery_state_entity_id: sensor.joana_pixel9pro_battery_state
      recipient: joana

- alias: Front Door Mailbox movement, send notification
  id: 5c3f86a6-9406-43fe-a7c3-c8552a69b350
  triggers:
    - trigger: state
      entity_id: event.front_door_mailbox_action
      not_from: "unavailable"
  conditions:
    - condition: state
      entity_id: binary_sensor.front_door_contact
      state: "off"
      for:
        seconds: 10
  actions:
    - service: script.send_notification
      data:
        message: "Movement detected on Front Door Mailbox"
        channel: "Automation"
        tag: "front_door_mailbox"

- alias: Set alarm state
  id: 2d53ff7e-e2b2-40e6-8362-33ede62ae3f6
  triggers:
    - trigger: homeassistant
      event: start
    - trigger: event
      event_type: automation_reloaded
    - trigger: state
      entity_id: binary_sensor.quiet_time
    - trigger: state
      entity_id: group.family
  actions:
    choose:
      - conditions:
          - "{{ is_state('binary_sensor.quiet_time', 'on') }}"
        sequence:
          - service: alarm_control_panel.alarm_arm_night
            entity_id: alarm_control_panel.home_alarm
      - conditions:
          - "{{ not is_state('group.family', 'home') }}"
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            entity_id: alarm_control_panel.home_alarm
    default:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm

- alias: Ender-3 V2 state changed, force full update
  id: 5336fd2c-f999-44a9-9380-7fac547309af
  mode: single
  triggers:
    - trigger: mqtt
      topic: "ender3v2/klipper/status"
      value_template: "{{ value_json.status.print_stats.state if 'print_stats' in value_json.status else None }}"
  actions:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.ender_3_v2_status

- alias: Trident 300 state changed, force full update
  id: 6e7c4434-c1cf-477b-b678-855489f4826b
  mode: single
  triggers:
    - trigger: mqtt
      topic: "trident300/klipper/status"
      value_template: "{{ value_json.status.print_stats.state if 'print_stats' in value_json.status else None }}"
  actions:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.trident_300_status

- alias: Ender-3 V2 print paused or complete, send notification
  id: 5b90fea9-37e6-4692-9c3f-5fdeb2e77fab
  triggers:
    - trigger: state
      id: print_is_paused_or_complete
      entity_id: sensor.ender_3_v2_current_state
      to:
        - "paused"
        - "complete"
    - trigger: state
      id: print_was_paused_or_complete
      entity_id: sensor.ender_3_v2_current_state
      from:
        - "paused"
        - "complete"
  actions:
    choose:
      - conditions:
          - condition: trigger
            id: print_is_paused_or_complete
        sequence:
          - service: script.send_notification
            data:
              recipient: "pedro"
              message: "Ender-3 V2 print {{ trigger.to_state.state }}!"
              channel: "Automation"
              tag: "ender3v2"
      - conditions:
          - condition: trigger
            id: print_was_paused_or_complete
        sequence:
          - service: script.clear_notification
            data:
              recipient: "pedro"
              channel: "Automation"
              tag: "ender3v2"

- alias: Trident 300 print paused or complete, send notification
  id: 8d26a910-90d8-4712-9148-c50a3e954787
  triggers:
    - trigger: state
      id: print_is_paused_or_complete
      entity_id: sensor.trident_300_current_state
      to:
        - "paused"
        - "complete"
    - trigger: state
      id: print_was_paused_or_complete
      entity_id: sensor.trident_300_current_state
      from:
        - "paused"
        - "complete"
  actions:
    choose:
      - conditions:
          - condition: trigger
            id: print_is_paused_or_complete
        sequence:
          - service: script.send_notification
            data:
              recipient: "pedro"
              message: "Trident 300 print {{ trigger.to_state.state }}!"
              channel: "Automation"
              tag: "trident300"
      - conditions:
          - condition: trigger
            id: print_was_paused_or_complete
        sequence:
          - service: script.clear_notification
            data:
              recipient: "pedro"
              channel: "Automation"
              tag: "trident300"

- alias: Indoor air quality poor, send notification
  id: f494166d-f979-46b9-9364-f8cab6492da3
  triggers:
    - trigger: numeric_state
      entity_id: sensor.node10_ikea_vindriktning_pm25
      above: 50
      for: "00:01:00"
  actions:
    - service: script.send_notification
      data:
        recipient: "pedro"
        title: "Air quality poor"
        message: "Better open a window!"
        color: "red"
        channel: "Alarm"
        tag: "air-quality"

- alias: Transmission download complete, send notification
  id: 1091a93a-be80-440b-a61d-ecd27ced6abb
  mode: queued
  triggers:
    - trigger: event
      event_type: transmission_downloaded_torrent
  actions:
    - service: script.send_notification
      data:
        recipient: "pedro"
        title: "Transmission download complete"
        message: "{{ trigger.event.data.name }}"
        channel: "Automation"
        tag: "transmission-{{ trigger.event.data.name }}"

- alias: Turn on TV requested, send magic packet
  id: bb2b09dd-5b40-4a94-a69a-b4808bed613f
  mode: single
  triggers:
    - trigger: webostv.turn_on
      entity_id: media_player.lg_smart_tv
  actions:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lg_smart_tv_mac

- alias: AdguardHome enabled after 2 minutes
  id: 3ba3ddc1-8f62-4413-9e23-42ae60cc3ba2
  triggers:
    - trigger: state
      entity_id: switch.adguard_protection
      to: "off"
      for: "00:02:00"
  actions:
    - service: switch.turn_on
      entity_id: switch.adguard_protection

- alias: OBS state changed, set Elgato Key Light Air state
  id: ad07265c-d8aa-441f-9170-b005b1a2e26b
  mode: queued
  triggers:
    - trigger: state
      id: obs_virtualcam_on
      entity_id: switch.obs_virtualcam
      to: "on"
    - trigger: state
      id: obs_virtualcam_off
      entity_id: switch.obs_virtualcam
      to: "off"
  actions:
    choose:
      - conditions:
          - condition: trigger
            id: obs_virtualcam_on
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.elgato_key_light_air
          - condition: "{{ is_state('light.lamp_7', 'on') }}"
          - service: light.turn_off
            data:
              entity_id: light.lamp_7
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.turn_on_lamp_on_obs_virtualcam_off
      - conditions:
          - condition: trigger
            id: obs_virtualcam_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.elgato_key_light_air
          - condition: "{{ is_state('input_boolean.turn_on_lamp_on_obs_virtualcam_off', 'on') }}"
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.turn_on_lamp_on_obs_virtualcam_off
          - service: light.turn_on
            data:
              entity_id: light.lamp_7

- alias: Set Zigbee2mqtt log level
  id: 6eb24622-8f61-4a04-bcc4-c24113c2c639
  triggers:
    - trigger: state
      entity_id: input_select.zigbee2mqtt_log_level
  actions:
    - service: mqtt.publish
      data:
        payload: >-
          {
            "options": {
              "advanced": {
                "log_level": "{{ trigger.to_state.state }}"
              }
            }
          }
        topic: "zigbee2mqtt/bridge/request/options"

- alias: Log Zigbee2mqtt errors
  id: 3f7282b9-5543-47da-966b-0751445c0273
  triggers:
    - trigger: mqtt
      topic: "zigbee2mqtt/bridge/log"
  conditions:
    - "{{ 'error' in trigger.payload_json.type }}"
  actions:
    - service: system_log.write
      data_template:
        message: "{{ trigger.payload_json }}"
        level: warning
