#- platform: workday
#  country: UK

- platform: ping
  name: Synology DS412+ NAS
  host: !secret synology_ds412plus_nas_host

- platform: ping
  name: Raspberry Pi 2 Model B
  host: !secret raspberry_pi_2_model_b_host

- platform: hikvision
  name: Living Room Camera
  host: !secret living_room_camera_host
  username: !secret living_room_camera_username
  password: !secret living_room_camera_password
  ssl: false

- platform: hikvision
  name: Lower Floor Camera
  host: !secret lower_floor_camera_host
  username: !secret lower_floor_camera_username
  password: !secret lower_floor_camera_password
  ssl: false

- platform: template
  sensors:
    lg_smart_tv_is_watching_live_tv:
      friendly_name: Live TV
      icon_template: mdi:television-classic
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') }}

    lg_smart_tv_is_watching_prime_video:
      friendly_name: Prime Video
      icon_template: mdi:amazon
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Amazon Prime Video') }}

    lg_smart_tv_is_watching_xbox_one_x:
      friendly_name: Xbox One X
      icon_template: mdi:microsoft-xbox
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Xbox One X') }}

    lg_smart_tv_is_watching_netflix:
      friendly_name: Netflix
      icon_template: mdi:netflix
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Netflix') }}

    lg_smart_tv_is_watching_plex:
      friendly_name: Plex
      icon_template: mdi:plex
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Plex') }}

    lg_smart_tv_is_watching_youtube:
      friendly_name: YouTube
      icon_template: mdi:youtube
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'YouTube') }}

    lg_smart_tv_is_watching_bbc_iplayer:
      friendly_name: BBC iPlayer
      icon_template: mdi:television-guide
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'BBC iPlayer') }}

    lg_smart_tv_is_watching_all_4:
      friendly_name: All 4
      icon_template: mdi:television-guide
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'All 4') }}

    lg_smart_tv_is_watching_bbc_one:
      friendly_name: BBC ONE
      icon_template: mdi:television-classic
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and state_attr('media_player.lg_smart_tv', 'media_title') in ['BBC ONE Lon', 'BBC ONE HD'] }}

    lg_smart_tv_is_watching_channel_4:
      friendly_name: Channel 4
      icon_template: mdi:television-classic
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and state_attr('media_player.lg_smart_tv', 'media_title') in ['Channel 4', 'Channel 4 HD'] }}

    lg_smart_tv_is_watching_bbc_news:
      friendly_name: BBC NEWS
      icon_template: mdi:television-classic
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and state_attr('media_player.lg_smart_tv', 'media_title') in ['BBC NEWS', 'BBC NEWS HD'] }}

    lg_smart_tv_is_watching_cbeebies:
      friendly_name: CBeebies
      icon_template: mdi:television-classic
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and state_attr('media_player.lg_smart_tv', 'media_title') in ['CBeebies', 'CBeebies HD'] }}

    external_ip_detected:
      friendly_name: External IP detected
      icon_template: >-
        {{ 'mdi:cloud-off-outline' if is_state('sensor.external_ip', 'unknown') else 'mdi:cloud-outline' }}
      value_template: >-
        {{ not(is_state('sensor.external_ip', 'unknown')) }}

    washing_machine_program_running:
      friendly_name: Washing Machine
      icon_template: mdi:washing-machine
      value_template: >-
        {{ states('sensor.washing_machine_smart_plug_power') | float > 0.5 }}
      delay_off: "00:01:00"
      delay_on: "00:00:30"

    mains_powered:
      friendly_name: Mains Power
      device_class: power
      value_template: >-
        {{ states('sensor.ups_input_voltage') | float > 1 }}

    ender_3_v2_printing:
      friendly_name: Ender-3 V2 Printing
      value_template: >-
        {{ states('sensor.ender_3_v2_current_state') in ['printing', 'paused'] }}
