include:
  domains:
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.backdoor_contact
    - binary_sensor.frontdoor_contact
    - binary_sensor.pirsensor_occupancy
    - light.lamp_1
    - light.lamp_2
    - light.lamp_3
    - light.lamp4
    - light.lamp5
    - light.lamp6
    - media_player.lg_smart_tv
    - person.joana
    - person.pedro
    - sensor.kidsbedroomclimate_humidity
    - sensor.kidsbedroomclimate_temperature
    - sensor.livingroomclimate_humidity
    - sensor.livingroomclimate_temperature
    - sensor.lowerfloorclimate_humidity
    - sensor.lowerfloorclimate_temperature
    - sensor.masterbedroomclimate_humidity
    - sensor.masterbedroomclimate_temperature
    - sensor.smartvibrationsensor_action
    - switch.smartplug1
    - switch.smartplug2
    - switch.smartplug3
    - switch.smartplug4
    - switch.smartplug5
    - switch.smartplug6
    - switch.smartplug7
