include:
  domains:
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.backdoor_contact
    - binary_sensor.frontdoor_contact
    - binary_sensor.pirsensor_occupancy
    - light.lamp_1
    - light.lamp_2
    - light.lamp_3
    - light.lamp_4
    - media_player.lg_smart_tv
    - person.joana
    - person.pedro
    - sensor.kidsbedroomclimate_humidity
    - sensor.kidsbedroomclimate_temperature
    - sensor.livingroomclimate_humidity
    - sensor.livingroomclimate_temperature
    - sensor.lowerfloorclimate_humidity
    - sensor.lowerfloorclimate_temperature
    - sensor.masterbedroomclimate_humidity
    - sensor.masterbedroomclimate_temperature
    - sensor.smartvibrationsensor_action
    - switch.smartplug1_switch
    - switch.smartplug2_switch
    - switch.smartplug3_switch
    - switch.smartplug4_switch
    - switch.smartplug5_switch
    - switch.smartplug6_switch
    - switch.smartplug7_switch
