- platform: group
  name: Living Room Lights
  entities:
    - light.lamp_1
    - light.lamp_2
    - light.lamp_3
    - light.kids_corner

- platform: group
  name: Master Bedroom Lights
  entities:
    - light.lamp_4
    - light.master_bedroom_dimmer

- platform: group
  name: Kids Bedroom Lights
  entities:
    - light.kids_bedroom_dimmer

- platform: mqtt
  name: Kids Corner
  schema: json
  command_topic: "zigbee2mqtt/KidsCornerGroup/set"
  state_topic: "zigbee2mqtt/KidsCornerGroup"
  brightness: true
