default: warn
filters:
  homeassistant.components.rest.data:
    - "All connection attempts failed"
  homeassistant.components.rest.sensor:
    - "Empty reply found when expecting JSON data"
  homeassistant.components.rest.switch:
    - "Connect call failed"
