sensor:
  - name: Zigbee2mqtt Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    value_template: >-
      {{ value_json.state }}
    icon: mdi:server-network

light:
  - name: Ender-3 V2
    schema: template
    availability_topic: "ender3v2/moonraker/status"
    availability_template: >
      {{ value_json.server }}
    state_topic: "ender3v2/klipper/state/output_pin lights/value"
    state_template: >-
      {% if value_json.value | float > 0 %}on{% else %}off{% endif %}
    command_topic: "ender3v2/moonraker/api/request"
    command_on_template: >-
      {
        "jsonrpc": "2.0",
        "method": "printer.gcode.script",
        "params": {
          "script": "SET_PIN PIN=\"lights\" VALUE={{ brightness | default(255) | multiply(1 / 255) | round(2) }}"
        }
      }
    command_off_template: >-
      {
        "jsonrpc": "2.0",
        "method": "printer.gcode.script",
        "params": {
          "script": "SET_PIN PIN=\"lights\" VALUE=0"
        }
      }
    brightness_template: >-
      {{ value_json.value | float | multiply(255) | round(0) }}

  - name: Trident 300
    schema: template
    availability_topic: "trident300/moonraker/status"
    availability_template: >
      {{ value_json.server }}
    state_topic: "trident300/klipper/state/output_pin caselight/value"
    state_template: >-
      {% if value_json.value | float > 0 %}on{% else %}off{% endif %}
    command_topic: "trident300/moonraker/api/request"
    command_on_template: >-
      {
        "jsonrpc": "2.0",
        "method": "printer.gcode.script",
        "params": {
          "script": "SET_PIN PIN=\"caselight\" VALUE={{ brightness | default(255) | multiply(1 / 255) | round(2) }}"
        }
      }
    command_off_template: >-
      {
        "jsonrpc": "2.0",
        "method": "printer.gcode.script",
        "params": {
          "script": "SET_PIN PIN=\"caselight\" VALUE=0"
        }
      }
    brightness_template: >-
      {{ value_json.value | float | multiply(255) | round(0) }}
