- id: pedro
  name: Pedro
  user_id: !secret pedro_user_id
  device_trackers:
    - device_tracker.pedro_pixel7pro
    - device_tracker.google_pixel_7_pro_pedro

- id: joana
  name: Joana
  user_id: !secret joana_user_id
  device_trackers:
    - device_tracker.joana_oneplus9
    - device_tracker.oneplus_9_joana
