- id: pedro
  name: Pedro
  user_id: !secret pedro_user_id
  device_trackers:
    - device_tracker.pedro_oneplus9pro
    - device_tracker.oneplus_9_pro_pedro

- id: joana
  name: Joana
  user_id: !secret joana_user_id
  device_trackers:
    - device_tracker.joana_oneplus7
    - device_tracker.oneplus_7_joana
