- id: pedro
  name: Pedro
  user_id: !secret pedro_user_id
  device_trackers:
    - device_tracker.pedro_pixel9pro
    - device_tracker.google_pixel_9_pro_pedro

- id: joana
  name: Joana
  user_id: !secret joana_user_id
  device_trackers:
    - device_tracker.joana_pixel9pro
    - device_tracker.google_pixel_9_pro_joana
