purge_keep_days: 5
db_url: !secret record_db_url

include:
  domains:
    - light
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.backdoor_contact
    - binary_sensor.external_ip_detected
    - binary_sensor.frontdoor_contact
    - binary_sensor.pirsensor_occupancy
    - person.joana
    - person.pedro
    - media_player.lg_smart_tv
    - sensor.cpu_temperature
    - sensor.external_ip
    - sensor.kids_bedroom_mold
    - sensor.kidsbedroomclimate_humidity
    - sensor.kidsbedroomclimate_temperature
    - sensor.laundryroomclimate_humidity
    - sensor.laundryroomclimate_temperature
    - sensor.living_room_mold
    - sensor.livingroomclimate_humidity
    - sensor.livingroomclimate_temperature
    - sensor.lowerfloorclimate_humidity
    - sensor.lowerfloorclimate_temperature
    - sensor.master_bedroom_mold
    - sensor.masterbedroomclimate_humidity
    - sensor.masterbedroomclimate_temperature
    - sensor.reported_ip
    - switch.smartplug1_switch
    - switch.smartplug2_switch
    - switch.smartplug3_switch
    - switch.smartplug4_switch
    - switch.smartplug5_switch
    - switch.smartplug6_switch
    - switch.smartplug7_switch
