purge_keep_days: 5
db_url: !secret record_db_url

include:
  domains:
    - light
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.back_door_contact
    - binary_sensor.external_ip_detected
    - binary_sensor.front_door_contact
    - binary_sensor.master_bedroom_pir_sensor_occupancy
    - media_player.lg_smart_tv
    - person.joana
    - person.pedro
    - sensor.external_ip
    - sensor.kids_bedroom_climate_humidity
    - sensor.kids_bedroom_climate_temperature
    - sensor.kids_bedroom_mold
    - sensor.kids_bedroom_smart_plug_energy
    - sensor.laundry_room_climate_humidity
    - sensor.laundry_room_climate_temperature
    - sensor.living_room_climate_humidity
    - sensor.living_room_climate_temperature
    - sensor.living_room_mold
    - sensor.lower_floor_climate_humidity
    - sensor.lower_floor_climate_temperature
    - sensor.lower_floor_smart_plug_energy
    - sensor.master_bedroom_climate_humidity
    - sensor.master_bedroom_climate_temperature
    - sensor.master_bedroom_mold
    - sensor.master_bedroom_smart_plug_energy
    - sensor.node02_power_meter
    - sensor.node02_total_energy
    - sensor.node02_total_energy_cost
    - sensor.node08_plant_1_moisture
    - sensor.node08_plant_1_soil_conductivity
    - sensor.node08_plant_1_temperature
    - sensor.node08_plant_2_moisture
    - sensor.node08_plant_2_soil_conductivity
    - sensor.node08_plant_2_temperature
    - sensor.reported_ip
    - sensor.washing_machine_smart_plug_energy
    - switch.kids_bedroom_smart_plug
    - switch.living_room_smart_plug
    - switch.lower_floor_smart_plug
    - switch.master_bedroom_smart_plug
    - switch.washing_machine_smart_plug
