- name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 90
  icon: mdi:home-variant

# - name: School
#   latitude: !secret school_latitude
#   longitude: !secret school_longitude
#   radius: 100
#   icon: mdi:school

# - name: Work
#   latitude: !secret work_latitude
#   longitude: !secret work_longitude
#   radius: 150
#   icon: mdi:domain

- name: Home (PT)
  latitude: !secret home_pt_latitude
  longitude: !secret home_pt_longitude
  radius: 150
  icon: mdi:home-variant

- name: Office (PT)
  latitude: !secret office_pt_latitude
  longitude: !secret office_pt_longitude
  radius: 180
  icon: mdi:domain

- name: Wood Play
  latitude: !secret park_latitude
  longitude: !secret park_longitude
  radius: 200
  icon: mdi:tree

- name: Porto Airport
  latitude: 41.247116
  longitude: -8.679150
  radius: 2000
  icon: mdi:airplane

- name: Maia, PT
  latitude: 41.244963
  longitude: -8.606497
  radius: 7000
  icon: mdi:flag

- name: Porto, PT
  latitude: 41.157944
  longitude: -8.629105
  radius: 12000
  icon: mdi:flag

- name: Seattle, USA
  latitude: 47.607135
  longitude: -122.242807
  radius: 15000
  icon: mdi:flag

- name: Paddington Station
  latitude: 51.51728
  longitude: -0.17775
  radius: 200
  icon: mdi:train

- name: Victoria Station
  latitude: 51.49486
  longitude: -0.14363
  radius: 150
  icon: mdi:train

- name: Gatwick Airport
  latitude: 51.15232
  longitude: -0.18917
  radius: 2000
  icon: mdi:airplane

- name: Heathrow Airport
  latitude: 51.47077
  longitude: -0.45465
  radius: 2500
  icon: mdi:airplane

- name: Stansted Airport
  latitude: 51.88550
  longitude: 0.24719
  radius: 2000
  icon: mdi:airplane
