blueprint:
  name: Device connectivity state change
  description: Process device connectivity state changes
  domain: automation
  input:
    on_off_entities:
      name: On/Off entities
      description: The entities to monitor for on/off state changes
      selector:
        entity:
    online_offline_entities:
      name: Online/Offline entities
      description: The entities to monitor for online/offline state changes
      selector:
        entity:
    warning_delay:
      name: Warning delay on device off/offline
      description: The time in seconds before sending a notification warning about a device being off/offline
      default: 60
      selector:
        number:
          min: 10
          max: 300
          step: 10
          unit_of_measurement: seconds

mode: queued

trigger:
  - platform: state
    entity_id: !input on_off_entities
    to: "off"
    for:
      seconds: !input warning_delay
  - platform: state
    entity_id: !input online_offline_entities
    to: "offline"
    for:
      seconds: !input warning_delay
  - platform: state
    entity_id: !input on_off_entities
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input online_offline_entities
    from: "offline"
    to: "online"

condition:
  - "{{ trigger.from_state.state != trigger.to_state.state }}"

action:
  - variables:
      device_entity: "{{ trigger.entity_id }}"
      device_state: "{{ trigger.to_state.state }}"
      device_friendly_name: "{{ trigger.to_state.attributes.friendly_name }}"
  - choose:
      - conditions:
          - "{{ device_state == 'on' or device_state == 'online' }}"
        sequence:
          - service: script.clear_notification
            data:
              recipient: "pedro"
              channel: "System"
              tag: "{{ device_entity }}-deviceoffline"

    default:
      - service: script.send_notification
        data:
          recipient: "pedro"
          message: "{{ device_friendly_name }} is offline."
          color: "red"
          channel: "System"
          tag: "{{ device_entity }}-deviceoffline"
