blueprint:
  name: Phone battery state
  description: Process phone battery state changes
  domain: automation
  input:
    battery_level_entity_id:
      name: Battery Level
      description: The phone battery level sensor
      selector:
        entity:
          integration: mobile_app
          domain: sensor
          device_class: battery
    battery_state_entity_id:
      name: Battery State
      description: The phone battery state sensor
      selector:
        entity:
          integration: mobile_app
          domain: sensor
          device_class: battery
    recipient:
      name: Recipient
      description: The notification recipient

variables:
  battery_level_entity_id: !input battery_level_entity_id

trigger:
  - platform: state
    id: battery_full
    entity_id: !input battery_state_entity_id
    to: "full"
  - platform: state
    id: battery_discharging
    entity_id: !input battery_state_entity_id
    to: "discharging"
  - platform: numeric_state
    id: battery_above_90
    entity_id: !input battery_level_entity_id
    above: 89

action:
  - choose:
      - conditions:
          - condition: trigger
            id: battery_full
        sequence:
          - service: script.send_notification
            data:
              recipient: !input recipient
              message: "Phone battery fully charged!"
              channel: "Phone"
              tag: "Battery"

      - conditions:
          - condition: trigger
            id: battery_above_90
        sequence:
          - service: script.send_notification
            data:
              recipient: !input recipient
              message: "Phone battery charged to {{ states(battery_level_entity_id) }}%!"
              channel: "Phone"
              tag: "Battery"

      - conditions:
          - condition: trigger
            id: battery_discharging
        sequence:
          - service: script.clear_notification
            data:
              recipient: !input recipient
              channel: "Phone"
              tag: "Battery"
