blueprint:
  name: Phone battery state
  description: Process phone battery state changes
  domain: automation
  input:
    battery_level_entity:
      name: Battery Level
      description: The phone battery level sensor
      selector:
        entity:
          integration: mobile_app
          domain: sensor
          device_class: battery
    battery_state_entity:
      name: Battery State
      description: The phone battery state sensor
      selector:
        entity:
          integration: mobile_app
          domain: sensor
          device_class: battery
    recipient:
      name: Recipient
      description: The notification recipient

variables:
  battery_state_entity: !input battery_state_entity
  battery_level_entity: !input battery_level_entity

trigger:
  - platform: state
    entity_id: !input battery_state_entity
  - platform: numeric_state
    entity_id: !input battery_level_entity
    above: 89

action:
  - variables:
      battery_state: "{{ states(battery_state_entity) }}"
      battery_level: "{{ states(battery_level_entity) }}"
  - choose:
      - conditions:
          - "{{ battery_state == 'full' }}"
        sequence:
          - service: script.send_notification
            data:
              recipient: !input recipient
              message: "Phone battery fully charged!"
              channel: "Phone"
              tag: "Battery"

      - conditions:
          - "{{ battery_state == 'charging' }}"
          - "{{ battery_level > 89 }}"
        sequence:
          - service: script.send_notification
            data:
              recipient: !input recipient
              message: "Phone battery charged to {{ battery_level }}%!"
              channel: "Phone"
              tag: "Battery"

      - conditions:
          - "{{ battery_state == 'discharging' }}"
        sequence:
          - service: script.clear_notification
            data:
              recipient: !input recipient
              channel: "Phone"
              tag: "Battery"
