title: Ambient
path: ambient
icon: mdi:thermometer
cards:
  - type: custom:vertical-stack-in-card
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.livingroomclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.livingroomclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.livingroomclimate_pressure
          - sensor.livingroomclimate_battery
          - sensor.livingroomclimate_linkquality

  - type: custom:vertical-stack-in-card
    title: Lower Floor
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.lowerfloorclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.lowerfloorclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.lowerfloorclimate_pressure
          - sensor.lowerfloorclimate_battery
          - sensor.lowerfloorclimate_linkquality

  - type: custom:vertical-stack-in-card
    title: Master Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.masterbedroomclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.masterbedroomclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.masterbedroomclimate_pressure
          - sensor.masterbedroomclimate_battery
          - sensor.masterbedroomclimate_linkquality

  - type: custom:vertical-stack-in-card
    title: Kids Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.kidsbedroomclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.kidsbedroomclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.kidsbedroomclimate_pressure
          - sensor.kidsbedroomclimate_battery
          - sensor.kidsbedroomclimate_linkquality
