title: Ambient
path: ambient
icon: mdi:thermometer
cards:
  - type: custom:vertical-stack-in-card
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.living_room_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.living_room_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.living_room_pressure
          - sensor.living_room_battery
          - sensor.living_room_link_quality

  - type: custom:vertical-stack-in-card
    title: Lower Floor
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.lower_floor_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.lower_floor_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.lower_floor_pressure
          - sensor.lower_floor_battery
          - sensor.lower_floor_link_quality

  - type: custom:vertical-stack-in-card
    title: Master Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.master_bedroom_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.master_bedroom_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.master_bedroom_pressure
          - sensor.master_bedroom_battery
          - sensor.master_bedroom_link_quality

  - type: custom:vertical-stack-in-card
    title: Kids Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.kids_bedroom_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.kids_bedroom_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.kids_bedroom_pressure
          - sensor.kids_bedroom_battery
          - sensor.kids_bedroom_link_quality
