title: Climate
path: climate
icon: mdi:thermometer
cards:
  - type: custom:vertical-stack-in-card
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.livingroomclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.livingroomclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.livingroomclimate_pressure
          - sensor.livingroomclimate_battery

  - type: custom:vertical-stack-in-card
    title: Lower Floor
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.lowerfloorclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.lowerfloorclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.lowerfloorclimate_pressure
          - sensor.lowerfloorclimate_battery

  - type: custom:vertical-stack-in-card
    title: Laundry Room
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.laundryroomclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.laundryroomclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.laundryroomclimate_pressure
          - sensor.laundryroomclimate_battery

  - type: custom:vertical-stack-in-card
    title: Master Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.masterbedroomclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.masterbedroomclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.masterbedroomclimate_pressure
          - sensor.masterbedroomclimate_battery

  - type: custom:vertical-stack-in-card
    title: Kids Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.kidsbedroomclimate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.kidsbedroomclimate_humidity
            graph: line
      - type: glance
        show_name: false
        entities:
          - sensor.kidsbedroomclimate_pressure
          - sensor.kidsbedroomclimate_battery

  - type: entities
    title: Mold Indicators
    show_header_toggle: false
    entities:
      - entity: sensor.living_room_mold
        name: Living Room
      - entity: sensor.master_bedroom_mold
        name: Master Bedroom
      - entity: sensor.kids_bedroom_mold
        name: Kids Bedroom
