title: Climate
path: climate
icon: mdi:thermometer
cards:
  - type: vertical-stack
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.living_room_climate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.living_room_climate_humidity
            graph: line
            limits: []
      - type: glance
        show_name: false
        entities:
          - sensor.living_room_climate_pressure
          - sensor.living_room_climate_battery

  - type: vertical-stack
    title: Lower Floor
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.lower_floor_climate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.lower_floor_climate_humidity
            graph: line
            limits: []
      - type: glance
        show_name: false
        entities:
          - sensor.lower_floor_climate_pressure
          - sensor.lower_floor_climate_battery

  - type: vertical-stack
    title: Laundry Room
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.laundry_room_climate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.laundry_room_climate_humidity
            graph: line
            limits: []
      - type: glance
        show_name: false
        entities:
          - sensor.laundry_room_climate_pressure
          - sensor.laundry_room_climate_battery

  - type: vertical-stack
    title: Master Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.master_bedroom_climate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.master_bedroom_climate_humidity
            graph: line
            limits: []
      - type: glance
        show_name: false
        entities:
          - sensor.master_bedroom_climate_pressure
          - sensor.master_bedroom_climate_battery

  - type: vertical-stack
    title: Kids Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.kids_bedroom_climate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.kids_bedroom_climate_humidity
            graph: line
            limits: []
      - type: glance
        show_name: false
        entities:
          - sensor.kids_bedroom_climate_pressure
          - sensor.kids_bedroom_climate_battery

  - type: vertical-stack
    title: Mold Indicators
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.living_room_mold
            name: Living Room
          - entity: sensor.master_bedroom_mold
            name: Master Bedroom
          - entity: sensor.kids_bedroom_mold
            name: Kids Bedroom
