title: Climate
path: climate
icon: mdi:thermometer
cards:
  - type: vertical-stack
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            color_thresholds:
              - value: 18.5
                color: "#0080FF"
              - value: 21.5
                color: "#FF0000"
            entities:
              - sensor.living_room_climate_temperature
          - type: custom:mini-graph-card
            name: Humidity
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            entities:
              - sensor.living_room_climate_humidity
      - type: glance
        show_name: false
        entities:
          - sensor.living_room_climate_pressure
          - sensor.living_room_climate_battery

  - type: vertical-stack
    title: Lower Floor
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            color_thresholds:
              - value: 18.5
                color: "#0080FF"
              - value: 21.5
                color: "#FF0000"
            entities:
              - sensor.lower_floor_climate_temperature
          - type: custom:mini-graph-card
            name: Humidity
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            entities:
              - sensor.lower_floor_climate_humidity
      - type: glance
        show_name: false
        entities:
          - sensor.lower_floor_climate_pressure
          - sensor.lower_floor_climate_battery

  - type: vertical-stack
    title: Laundry Room
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            color_thresholds:
              - value: 18.5
                color: "#0080FF"
              - value: 21.5
                color: "#FF0000"
            entities:
              - sensor.laundry_room_climate_temperature
          - type: custom:mini-graph-card
            name: Humidity
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            entities:
              - sensor.laundry_room_climate_humidity
      - type: glance
        show_name: false
        entities:
          - sensor.laundry_room_climate_pressure
          - sensor.laundry_room_climate_battery

  - type: vertical-stack
    title: Master Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            color_thresholds:
              - value: 18.5
                color: "#0080FF"
              - value: 21.5
                color: "#FF0000"
            entities:
              - sensor.master_bedroom_climate_temperature
          - type: custom:mini-graph-card
            name: Humidity
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            entities:
              - sensor.master_bedroom_climate_humidity
      - type: glance
        show_name: false
        entities:
          - sensor.master_bedroom_climate_pressure
          - sensor.master_bedroom_climate_battery

  - type: vertical-stack
    title: Kids Bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            color_thresholds:
              - value: 18.5
                color: "#0080FF"
              - value: 21.5
                color: "#FF0000"
            entities:
              - sensor.kids_bedroom_climate_temperature
          - type: custom:mini-graph-card
            name: Humidity
            font_size: 80
            hours_to_show: 24
            points_per_hour: 1
            entities:
              - sensor.kids_bedroom_climate_humidity
      - type: glance
        show_name: false
        entities:
          - sensor.kids_bedroom_climate_pressure
          - sensor.kids_bedroom_climate_battery

  - type: vertical-stack
    title: Ambient
    cards:
      - type: custom:mini-graph-card
        name: Indoor air quality
        font_size: 80
        hours_to_show: 24
        points_per_hour: 1
        show:
          labels: true
        color_thresholds:
          - value: 35
            color: green
          - color: yellow
          - value: 85
            color: red
        entities:
          - sensor.node10_ikea_vindriktning_pm25

  - type: vertical-stack
    title: Mold Indicators
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.living_room_mold
            name: Living Room
          - entity: sensor.master_bedroom_mold
            name: Master Bedroom
          - entity: sensor.kids_bedroom_mold
            name: Kids Bedroom
