title: Lights
path: lights
icon: mdi:lightbulb-outline
cards:
  - type: entities
    title: Living Room
    show_header_toggle: false
    entities:
      - entity: light.lamp_1
      - entity: light.lamp_2
      - entity: light.lamp_3
      - entity: light.kids_corner

  - type: entities
    title: Master Bedroom
    show_header_toggle: false
    entities:
      - entity: light.masterbedroomdimmer_light
        name: Ceiling dimmer
      - entity: light.lamp4_light

  - type: entities
    title: Kids Bedroom
    show_header_toggle: false
    entities:
      - entity: light.kidsbedroomdimmer_light
        name: Ceiling dimmer
