title: Main
path: main
icon: mdi:home-outline
badges:
  - person.pedro
  - person.joana
  - sensor.eastern_time_zone
  - sensor.pacific_time_zone
cards:
  - type: glance
    title: Living Room
    columns: 4
    entities:
      - entity: light.living_room
        name: Lights
        tap_action:
          action: navigate
          navigation_path: /lovelace/lights
      - entity: sensor.livingroomclimate_temperature
        name: Temperature
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: sensor.livingroomclimate_humidity
        name: Humidity
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: camera.living_room_camera
        name: Camera
      - entity: switch.smartplug1_switch
        name: Smart Plug
        tap_action:
          action: navigate
          navigation_path: /lovelace/plugs
      - entity: binary_sensor.frontdoor_contact
      - entity: binary_sensor.backdoor_contact
      - entity: media_player.lg_smart_tv
        tap_action:
          action: navigate
          navigation_path: /lovelace/media

  - type: glance
    title: Lower Floor
    columns: 4
    entities:
      - entity: binary_sensor.washing_machine_program_running
        name: Washer
      - entity: sensor.lowerfloorclimate_temperature
        name: Temperature
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: sensor.lowerfloorclimate_humidity
        name: Humidity
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: camera.lower_floor_camera
        name: Camera
      - entity: switch.smartplug2_switch
        name: Smart Plug
        tap_action:
          action: navigate
          navigation_path: /lovelace/plugs

  - type: glance
    title: Master Bedroom
    columns: 4
    entities:
      - entity: light.master_bedroom
        name: Lights
        tap_action:
          action: navigate
          navigation_path: /lovelace/lights
      - entity: sensor.masterbedroomclimate_temperature
        name: Temperature
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: sensor.masterbedroomclimate_humidity
        name: Humidity
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: switch.smartplug7_switch
        name: Smart Plug
        tap_action:
          action: navigate
          navigation_path: /lovelace/plugs

  - type: glance
    title: Kids Bedroom
    columns: 4
    entities:
      - entity: sensor.kidsbedroomclimate_temperature
        name: Temperature
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: sensor.kidsbedroomclimate_humidity
        name: Humidity
        tap_action:
          action: navigate
          navigation_path: /lovelace/climate
      - entity: switch.smartplug4_switch
        name: Smart Plug
        tap_action:
          action: navigate
          navigation_path: /lovelace/plugs

  - type: glance
    title: Local
    columns: 4
    entities:
    - entity: sensor.victoria
    - entity: sensor.bakerloo
    - entity: sensor.london_overground
    - entity: sensor.islington

  - type: weather-forecast
    title: Weather
    entity: weather.dark_sky

  - type: glance
    title: Network
    columns: 4
    entities:
      - entity: sensor.external_ip
      - entity: sensor.reported_ip
      - entity: sensor.zigbee2mqtt_bridge_state
        name: Zigbee2mqtt
      - entity: input_boolean.pi_hole_paused
        name: Pause Pi-hole
        tap_action:
          action: call-service
          service: input_boolean.turn_on
          service_data:
            entity_id: input_boolean.pi_hole_paused

#  - type: glance
#    title: Others
#    columns: 4
#    entities:
#      - entity: sensor.eastern_time_zone
#        name: Eastern Time
#      - entity: sensor.pacific_time_zone
#        name: Pacific Time
#      - entity: sensor.moon
#      - entity: sun.sun
