title: Main
icon: mdi:home-outline
badges:
  - person.pedro
  - person.joana
  - sensor.eastern_time_zone
  - sensor.pacific_time_zone
cards:
  - type: glance
    title: Living Room
    columns: 4
    entities:
      - entity: light.living_room
        name: Lights
        tap_action:
          action: toggle
      - entity: sensor.living_room_temperature
        name: Temperature
      - entity: sensor.living_room_humidity
        name: Humidity
      - entity: switch.living_room_outlet
        name: Outlet
        tap_action:
          action: toggle
      - entity: binary_sensor.front_door_state
      - entity: binary_sensor.back_door_state
      - entity: media_player.lg_smart_tv
  
  - type: glance
    title: Lower Floor
    columns: 4
    entities:
      - entity: switch.lower_floor_outlet
        name: Outlet
        tap_action:
          action: toggle

  - type: glance
    title: Master Bedroom
    columns: 4
    entities:
      - entity: light.master_bedroom
        name: Lights
        tap_action:
          action: toggle
      - entity: sensor.master_bedroom_temperature
        name: Temperature
      - entity: sensor.master_bedroom_humidity
        name: Humidity

  - type: glance
    title: Kids Bedroom
    columns: 4
    entities:
      - entity: sensor.kids_bedroom_temperature
        name: Temperature
      - entity: sensor.kids_bedroom_humidity
        name: Humidity

  - type: weather-forecast
    title: Weather
    entity: weather.dark_sky

#  - type: glance
#    title: Others
#    columns: 4
#    entities:
#      - entity: sensor.eastern_time_zone
#        name: Eastern Time
#      - entity: sensor.pacific_time_zone
#        name: Pacific Time
#      - entity: sensor.moon
#      - entity: sun.sun
