title: Map
path: map
icon: mdi:map-outline
panel: true
cards:
  - type: map
    title: Map
    dark_mode: true
    entities:
      - person.pedro
      - person.joana
      - zone.home
      - zone.work
      - zone.paddington_station
      - zone.victoria_station
