type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_live_tv
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "Live TV"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_netflix
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "Netflix"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_prime_video
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "Amazon Prime Video"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_plex
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "Plex"

  - type: horizontal-stack
    cards:
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_xbox_series_x
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "Xbox Series X"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_youtube
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "YouTube"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_bbc_iplayer
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "BBC iPlayer"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_all_4
        tap_action:
          action: call-service
          service: script.watch_on_lg_smart_tv
          service_data:
            source: "All 4"

  - type: horizontal-stack
    cards:
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_bbc_one
        tap_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "BBC ONE Lon HD"
        hold_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "BBC ONE Lon"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_bbc_news
        tap_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "BBC NEWS"
        hold_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "BBC NEWS"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_channel_4
        tap_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "Channel 4 HD"
        hold_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "Channel 4"
      - type: button
        entity: binary_sensor.lg_smart_tv_is_watching_cbeebies
        tap_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "CBeebies HD"
        hold_action:
          action: call-service
          service: media_player.play_media
          service_data:
            source: "Live TV"
            channel: "CBeebies"

  - type: horizontal-stack
    cards:
      - type: button
        entity: switch.lg_smart_tv_volume_mute
        name: " "
        icon: mdi:volume-mute
        tap_action:
          action: toggle
      - type: button
        icon: mdi:volume-low
        tap_action:
          action: call-service
          service: media_player.volume_down
          service_data:
            entity_id: media_player.lg_smart_tv
      - type: button
        icon: mdi:volume-high
        tap_action:
          action: call-service
          service: media_player.volume_up
          service_data:
            entity_id: media_player.lg_smart_tv

  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:power
        tap_action:
          action: call-service
          service: media_player.turn_off
          service_data:
            entity_id: media_player.lg_smart_tv
      - type: button
        icon: mdi:skip-previous
        tap_action:
          action: call-service
          service: media_player.media_previous_track
          service_data:
            entity_id: media_player.lg_smart_tv
      - type: button
        entity: sensor.lg_smart_tv_is_playing
        name: " "
        state_color: false
        tap_action:
          action: call-service
          service: media_player.media_play_pause
          service_data:
            entity_id: media_player.lg_smart_tv
      - type: button
        icon: mdi:skip-next
        tap_action:
          action: call-service
          service: media_player.media_next_track
          service_data:
            entity_id: media_player.lg_smart_tv
