title: People
path: people
icon: mdi:account-outline
cards:
  - type: glance
    title: Pedro's Phone
    entities:
      - entity: person.pedro
        name: Location
        hold_action:
          action: call-service
          service: notify.mobile_app_pedro_oneplus9pro
          service_data:
            message: "request_location_update"
      - entity: device_tracker.pedro_oneplus9pro
        name: GPS
        icon: mdi:crosshairs-gps
      - entity: device_tracker.oneplus_9_pro_pedro
        name: WiFi
        icon: mdi:wifi
      - entity: sensor.pedro_oneplus9pro_battery_level
        name: Battery

  - type: glance
    title: Joana's Phone
    entities:
      - entity: person.joana
        name: Location
        hold_action:
          action: call-service
          service: notify.mobile_app_joana_oneplus7
          service_data:
            message: "request_location_update"
      - entity: device_tracker.joana_oneplus7
        name: GPS
        icon: mdi:crosshairs-gps
      - entity: device_tracker.oneplus_7_joana
        name: WiFi
        icon: mdi:wifi
      - entity: sensor.joana_oneplus7_battery_level
        name: Battery

  - type: alarm-panel
    entity: alarm_control_panel.home_alarm
