title: People
path: people
icon: mdi:account-outline
cards:
  - type: glance
    title: Pedro's Phone
    entities:
      - entity: person.pedro
        name: Location
      - entity: device_tracker.pedro_oneplus7pro
        name: GPS
        icon: mdi:crosshairs-gps
      - entity: device_tracker.oneplus_7_pro_pedro
        name: WiFi
        icon: mdi:wifi
      - entity: sensor.pedro_oneplus7pro_battery
        name: Battery

  - type: glance
    title: Joana's Phone
    entities:
      - entity: person.joana
        name: Location
      - entity: device_tracker.joana_oneplus7
        name: GPS
        icon: mdi:crosshairs-gps
      - entity: device_tracker.oneplus_7_joana
        name: WiFi
        icon: mdi:wifi
      - entity: sensor.joana_oneplus7_battery
        name: Battery
