title: People
path: people
icon: mdi:account-outline
cards:
  - type: glance
    title: Pedro's Phone
    entities:
      - entity: person.pedro
        name: Location
      - entity: device_tracker.pedro_oneplus6
        name: GPS
        icon: mdi:crosshairs-gps
      - entity: device_tracker.pedro_oneplus6_wifi
        name: WiFi
        icon: mdi:wifi
      - entity: sensor.pedro_oneplus6_battery
        name: Battery

  - type: glance
    title: Joana's Phone
    entities:
      - entity: person.joana
        name: Location
      - entity: device_tracker.joana_oneplus6
        name: GPS
        icon: mdi:crosshairs-gps
      - entity: device_tracker.joana_oneplus6_wifi
        name: WiFi
        icon: mdi:wifi
      - entity: sensor.joana_oneplus6_battery
        name: Battery
