title: Plants
path: plants
icon: mdi:flower-outline
cards:
  - type: entities
    title: Bromy
    show_header_toggle: false
    state_color: true
    entities:
      - entity: sensor.plant_sensor_f6ee_moisture
        name: Moisture
      - entity: sensor.plant_sensor_f6ee_conductivity
        name: Conductivity
      - entity: sensor.plant_sensor_f6ee_temperature
        name: Temperature
      - entity: sensor.plant_sensor_f6ee_illuminance
        name: Illuminance
  - type: entities
    title: Lily
    show_header_toggle: false
    state_color: true
    entities:
      - entity: sensor.plant_sensor_f491_moisture
        name: Moisture
      - entity: sensor.plant_sensor_f491_conductivity
        name: Conductivity
      - entity: sensor.plant_sensor_f491_temperature
        name: Temperature
      - entity: sensor.plant_sensor_f491_illuminance
        name: Illuminance
