title: Plugs
path: plugs
icon: mdi:flash
cards:
  - type: entities
    title: Smart Plugs
    show_header_toggle: false
    entities:
      - entity: switch.smartplug1_switch
      - entity: switch.smartplug2_switch
      - entity: switch.smartplug3_switch
