title: Plugs
path: plugs
icon: mdi:flash
cards:
  - type: entities
    title: Smart Plugs
    show_header_toggle: false
    state_color: true
    entities:
      - entity: switch.living_room_smart_plug
      - type: divider
      - entity: switch.lower_floor_smart_plug
      - type: divider
      - entity: switch.master_bedroom_smart_plug
      - entity: sensor.master_bedroom_smart_plug_power
        name: Power
      - type: divider
      - entity: switch.kids_bedroom_smart_plug
      - entity: sensor.kids_bedroom_smart_plug_power
        name: Power
      - type: divider
      - entity: switch.washing_machine_smart_plug
      - entity: sensor.washing_machine_smart_plug_power
        name: Power
