title: Plugs
path: plugs
icon: mdi:flash-outline
cards:
  - type: entities
    title: Smart Plugs
    show_header_toggle: false
    state_color: true
    entities:
      - type: custom:multiple-entity-row
        entity: switch.living_room_smart_plug
        name: Living Room
        toggle: true
        state_color: true
        entities:
          - entity: sensor.living_room_smart_plug_power
            name: " "
      - entity: switch.kids_corner_smart_plug
        name: Kids Corner
      - type: custom:multiple-entity-row
        entity: switch.lower_floor_smart_plug
        name: Lower floor
        toggle: true
        state_color: true
        entities:
          - entity: sensor.lower_floor_smart_plug_power
            name: " "
      - type: custom:multiple-entity-row
        entity: switch.master_bedroom_smart_plug
        name: Master Bedroom
        toggle: true
        state_color: true
        entities:
          - entity: sensor.master_bedroom_smart_plug_power
            name: " "
      - type: custom:multiple-entity-row
        entity: switch.kids_bedroom_smart_plug
        name: Kids Bedroom
        toggle: true
        state_color: true
        entities:
          - entity: sensor.kids_bedroom_smart_plug_power
            name: " "
      - type: custom:multiple-entity-row
        entity: switch.washing_machine_smart_plug
        name: Washing Machine
        toggle: true
        state_color: true
        entities:
          - entity: sensor.washing_machine_smart_plug_power
            name: " "
