smart_home:
  endpoint: https://api.eu.amazonalexa.com/v3/events
  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret
  filter:
    include_entities:
      - binary_sensor.back_door_state
      - binary_sensor.front_door_state
      - media_player.lg_smart_tv
      - sensor.kids_bedroom_temperature
      - sensor.living_room_temperature
      - sensor.master_bedroom_temperature
      - script.watch_netflix_on_lg_smart_tv
      - script.watch_plex_on_lg_smart_tv
      - script.watch_bbc_one_on_lg_smart_tv
      - script.watch_bbc_news_on_lg_smart_tv
      - script.watch_channel_4_on_lg_smart_tv
      - switch.living_room_smart_plug
      - switch.lower_floor_smart_plug
    exclude_domains:
      - automation
      - binary_sensor
      - camera
      - device_tracker
      - group
      - hangouts
      - input_boolean
      - input_number
      - input_select
      - light
      - media_player
      - person
      - sensor
      - sun
      - switch
      - timer
      - updater
      - weather
      - weblink
      - zigbee2mqtt_networkmap
      - zone
  entity_config:
    binary_sensor.back_door_state:
      name: Back Door
    binary_sensor.front_door_state:
      name: Front Door
    media_player.lg_smart_tv:
      name: TV
    sensor.kids_bedroom_temperature:
      name: Kids Bedroom Temperature
    sensor.living_room_temperature:
      name: Living Room Temperature
    sensor.master_bedroom_temperature:
      name: Master Bedroom Temperature
    script.watch_netflix_on_lg_smart_tv:
      name: Netflix
    script.watch_plex_on_lg_smart_tv:
      name: Plex
    script.watch_bbc_one_on_lg_smart_tv:
      name: BBC One
    script.watch_bbc_news_on_lg_smart_tv:
      name: BBC News
    script.watch_channel_4_on_lg_smart_tv:
      name: Channel 4
    switch.living_room_smart_plug:
      name: Smart Plug 1
      display_categories: SMARTPLUG
    switch.lower_floor_smart_plug:
      name: Smart Plug 2
      display_categories: SMARTPLUG
