smart_home:
  endpoint: https://api.eu.amazonalexa.com/v3/events
  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret
  filter:
    include_entities:
      - binary_sensor.backdoor_contact
      - binary_sensor.frontdoor_contact
      - light.kidsbedroomdimmer_light
      - light.masterbedroomdimmer_light
      - media_player.lg_smart_tv
      - sensor.kidsbedroomclimate_temperature
      - sensor.livingroomclimate_temperature
      - sensor.lowerfloorclimate_temperature
      - sensor.masterbedroomclimate_temperature
      - script.watch_netflix_on_lg_smart_tv
      - script.watch_plex_on_lg_smart_tv
      - script.watch_bbc_one_on_lg_smart_tv
      - script.watch_bbc_news_on_lg_smart_tv
      - script.watch_cbeebies_on_lg_smart_tv
      - script.watch_channel_4_on_lg_smart_tv
      - switch.smartplug1_switch
      - switch.smartplug2_switch
      - switch.smartplug3_switch
      - switch.smartplug4_switch
      - switch.smartplug5_switch
      - switch.smartplug6_switch
      - switch.smartplug7_switch
    exclude_domains:
      - automation
      - binary_sensor
      - camera
      - device_tracker
      - group
      - hangouts
      - input_boolean
      - input_number
      - input_select
      - light
      - media_player
      - person
      - script
      - sensor
      - sun
      - switch
      - timer
      - updater
      - weather
      - weblink
      - zigbee2mqtt_networkmap
      - zone
  entity_config:
    binary_sensor.backdoor_contact:
      name: Back Door
    binary_sensor.frontdoor_contact:
      name: Front Door
    light.kidsbedroomdimmer_light:
      name: Kids Bedroom Dimmer
    light.masterbedroomdimmer_light:
      name: Master Bedroom Dimmer
    media_player.lg_smart_tv:
      name: TV
    sensor.kidsbedroomclimate_temperature:
      name: Kids Bedroom Temperature
    sensor.livingroomclimate_temperature:
      name: Living Room Temperature
    sensor.lowerfloorclimate_temperature:
      name: Lower Floor Temperature
    sensor.masterbedroomclimate_temperature:
      name: Master Bedroom Temperature
    script.watch_netflix_on_lg_smart_tv:
      name: Netflix
    script.watch_plex_on_lg_smart_tv:
      name: Plex
    script.watch_bbc_one_on_lg_smart_tv:
      name: BBC One
    script.watch_bbc_news_on_lg_smart_tv:
      name: BBC News
    script.watch_cbeebies_on_lg_smart_tv:
      name: CBeebies
    script.watch_channel_4_on_lg_smart_tv:
      name: Channel 4
    switch.smartplug1_switch:
      name: Smart Plug 1
      display_categories: SMARTPLUG
    switch.smartplug2_switch:
      name: Smart Plug 2
      display_categories: SMARTPLUG
    switch.smartplug3_switch:
      name: Smart Plug 3
      display_categories: SMARTPLUG
    switch.smartplug4_switch:
      name: Smart Plug 4
      display_categories: SMARTPLUG
    switch.smartplug5_switch:
      name: Smart Plug 5
      display_categories: SMARTPLUG
    switch.smartplug6_switch:
      name: Smart Plug 6
      display_categories: SMARTPLUG
    switch.smartplug7_switch:
      name: Smart Plug 7
      display_categories: SMARTPLUG
