- alias: Sensor low battery, send notification
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.back_door_battery
        - sensor.front_door_battery
        - sensor.living_room_battery
        - sensor.kids_bedroom_battery
        - sensor.master_bedroom_battery
      below: 20
  action:
    - service: persistent_notification.create
      data:
        title: "Device with low battery"
        message: >-
          "The {{ trigger.to_state.attributes.friendly_name }} sensor has low battery!"

- alias: Device offline, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.unifi_cloud_key_gen2_plus
        - binary_sensor.philips_hue_bridge_2_1
        - binary_sensor.synology_ds412_nas
        - binary_sensor.raspberry_pi_2_model_b
        - binary_sensor.amazon_fire_cube
      from: "on"
      to: "off"
      for:
        seconds: 60
  action:
    - service: script.send_notification
      data_template:
        message: "ALERT: {{ trigger.to_state.attributes.friendly_name }} is offline."

- alias: CPU temperature above 42, send notification
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.cpu_temperature
      above: 42
      for:
        minutes: 10
  action:
    - service: script.send_notification
      data_template:
        message: "ALERT: CPU temperature is above 42°C!"

- alias: Door open, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.back_door_state
        - binary_sensor.front_door_state
      from: "off"
      to: "on"
  action:
    - service: script.send_notification
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} is open!"

- alias: Door open for 5 minutes, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.back_door_state
        - binary_sensor.front_door_state
      from: "off"
      to: "on"
      for:
        minutes: 5
  action:
    - service: script.send_notification
      data_template:
        message: "ALERT: {{ trigger.to_state.attributes.friendly_name }} is still open!"

- alias: Back Door open, turn on Lamp 3
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_state
      from: "off"
      to: "on"
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.lamp_3
        state: "off"
      - condition: state
        entity_id: input_boolean.turn_off_lamp_3_on_back_door_close
        state: "on"
  action:
    - service: light.turn_on
      entity_id: light.lamp_3
    - service: input_boolean.turn_on
      entity_id: input_boolean.turn_off_lamp_3_on_back_door_close

- alias: Back Door closed for 30s, turn off Lamp 3
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_state
      to: "off"
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.turn_off_lamp_3_on_back_door_close
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.turn_off_lamp_3_on_back_door_close
    - service: light.turn_off
      entity_id: light.lamp_3

- alias: Front Door open, turn on Lamp 2
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_state
      from: "off"
      to: "on"
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.lamp_2
        state: "off"
      - condition: state
        entity_id: input_boolean.turn_off_lamp_2_on_front_door_close
        state: "on"
  action:
    - service: light.turn_on
      entity_id: light.lamp_2
    - service: input_boolean.turn_on
      entity_id: input_boolean.turn_off_lamp_2_on_front_door_close

- alias: Front Door closed, turn off Lamp 3 after 30s
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_state
      to: "off"
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.turn_off_lamp_2_on_front_door_close
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.turn_off_lamp_2_on_front_door_close
    - service: light.turn_off
      entity_id: light.lamp_2

- alias: Update available, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: script.send_notification
    data_template:
      message: "Home Assistant update available!"
