- alias: Home Assistant started, set default theme
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: slate

- alias: Sensor low battery, send notification
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.back_door_battery
        - sensor.front_door_battery
        - sensor.front_door_mailbox_battery
        - sensor.living_room_battery
        - sensor.kids_bedroom_battery
        - sensor.master_bedroom_battery
      below: 20
  action:
    - service: persistent_notification.create
      data:
        title: "Device with low battery"
        message: "The {{ trigger.to_state.attributes.friendly_name }} sensor has low battery!"

- alias: Device offline, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.unifi_cloud_key_gen2_plus
        - binary_sensor.philips_hue_bridge_2_1
        - binary_sensor.synology_ds412_nas
        - binary_sensor.raspberry_pi_2_model_b
      from: "on"
      to: "off"
      for:
        seconds: 60
    - platform: state
      entity_id:
        - sensor.zigbee2mqtt_bridge_state
      from: "online"
      to: "offline"
      for:
        seconds: 60
  action:
    - service: script.send_notification_pedro
      data_template:
        message: "ALERT: {{ trigger.to_state.attributes.friendly_name }} is offline."

- alias: CPU temperature above 42, send notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.cpu_temperature
      above: 42
      for:
        minutes: 10
  action:
    - service: script.send_notification_pedro
      data_template:
        message: "ALERT: CPU temperature is above 42°C!"

- alias: Door open, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_state
        - binary_sensor.front_door_state
      from: "off"
      to: "on"
  action:
    - service: script.send_notification_with_living_room_camera_snapshot
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} is open!"

- alias: Door open for 5 minutes, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_state
        - binary_sensor.front_door_state
      from: "off"
      to: "on"
      for:
        minutes: 5
  action:
    - service: script.send_notification_pedro
      data_template:
        message: "ALERT: {{ trigger.to_state.attributes.friendly_name }} is still open!"
    - service: input_boolean.turn_on
      data_template:
        entity_id: "{{ trigger.to_state.attributes.send_notification_entity_id }}"

- alias: Door open, turn on lamp
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_state
        - binary_sensor.front_door_state
      from: "off"
      to: "on"
  condition:
    - condition: template
      value_template: >-
        {{ is_state(trigger.to_state.attributes.lamp_entity_id, 'off') or is_state(trigger.to_state.attributes.lamp_off_entity_id, 'on') }}
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_entity_id }}"
    - service: input_boolean.turn_on
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_off_entity_id }}"

- alias: Door closed after 5 minutes, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_state
        - binary_sensor.front_door_state
      to: "off"
  condition:
    - condition: template
      value_template: >-
        {{ is_state(trigger.to_state.attributes.send_notification_entity_id, 'on') }}
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: "{{ trigger.to_state.attributes.send_notification_entity_id }}"
    - service: script.send_notification_pedro
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} is closed!"

- alias: Door closed for 30s, turn off lamp
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door_state
        - binary_sensor.front_door_state
      to: "off"
      for:
        seconds: 30
  condition:
    - condition: template
      value_template: >-
        {{ is_state(trigger.to_state.attributes.lamp_off_entity_id, 'on') }}
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_off_entity_id }}"
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_entity_id }}"

- alias: Front Door Mailbox movement, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.front_door_mailbox
      from: ""
  action:
    - service: script.send_notification_all
      data_template:
        message: "Movement detected on Front Door Mailbox"

- alias: Update available, send notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: script.send_notification_pedro
      data_template:
        message: "Home Assistant update available!"

- alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: debug
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: warn
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: error
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: info
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
        topic: "zigbee2mqtt/bridge/config/log_level"
