- alias: Home Assistant started, set default theme
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: "Google Dark Theme"

- alias: Sensor low battery, send notification
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.backdoor_battery
        - sensor.frontdoor_battery
        - sensor.frontdoormailbox_battery
        - sensor.kidsbedroomclimate_battery
        - sensor.laundryroomclimate_battery
        - sensor.livingroomclimate_battery
        - sensor.lowerfloorclimate_battery
        - sensor.masterbedroomclimate_battery
        - sensor.smartswitch_battery
        - sensor.smartvibrationsensor_battery
      below: 20
  action:
    - service: persistent_notification.create
      data_template:
        title: "Device with low battery"
        message: "The {{ trigger.to_state.attributes.friendly_name }} sensor has low battery!"

- alias: Smart Plug on with low power for 2 minutes, turn off
  trigger:
    - platform: template
      value_template: >-
        {{ is_state('switch.smartplug4_switch', 'on') and states('sensor.smartplug4_power') | float < 0.3 }}
      for:
        minutes: 2
    - platform: template
      value_template: >-
        {{ is_state('switch.smartplug7_switch', 'on') and states('sensor.smartplug7_power') | float < 0.3 }}
      for:
        minutes: 2
  action:
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

- alias: Device offline, send notification
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.philips_hue_bridge_2_1
        - binary_sensor.raspberry_pi_2_model_b
        - binary_sensor.synology_ds412_nas
        - binary_sensor.unifi_cloud_key_gen2_plus
      to: "off"
      for:
        minutes: 1
    - platform: state
      entity_id:
        - sensor.zigbee2mqtt_bridge_state
      to: "offline"
      for:
        minutes: 1
  action:
    - service: script.send_notification
      data_template:
        recipient: "pedro"
        message: "ALERT: {{ trigger.to_state.attributes.friendly_name }} is offline."
        channel: "System"
        tag: "{{ trigger.entity_id }}-deviceoffline"

- alias: Device online, clear notification
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.philips_hue_bridge_2_1
        - binary_sensor.raspberry_pi_2_model_b
        - binary_sensor.synology_ds412_nas
        - binary_sensor.unifi_cloud_key_gen2_plus
      from: "off"
      to: "on"
    - platform: state
      entity_id:
        - sensor.zigbee2mqtt_bridge_state
      from: "offline"
      to: "online"
  action:
    - service: script.clear_notification
      data_template:
        recipient: "pedro"
        channel: "System"
        tag: "{{ trigger.entity_id }}-deviceoffline"

- alias: External IP doesn't match reported IP, update reported IP
  trigger:
    - platform: state
      entity_id:
        - sensor.external_ip
        - sensor.reported_ip
  condition:
    - condition: template
      value_template: >-
        {{ not(is_state('sensor.external_ip', 'unknown') or is_state('sensor.reported_ip', 'unknown')) and states('sensor.external_ip') != states('sensor.reported_ip') }}
  action:
    - service: script.update_reported_ip

- alias: Washing Machine program finished, send notification
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_program_running
      to: "off"
  action:
    - service: script.send_notification
      data:
        message: "Washing Machine program finished!"
        channel: "Automation"
        tag: "washingmachine"

- alias: Door open, send notification
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backdoor_contact
        - binary_sensor.frontdoor_contact
      to: "on"
  action:
    - service: script.send_notification
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} is open!"
        channel: "Alarm"
        tag: "{{ trigger.entity_id }}"

- alias: Door open and lamp off, turn on lamp
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backdoor_contact
        - binary_sensor.frontdoor_contact
      to: "on"
  condition:
    - condition: template
      value_template: >-
        {{ is_state(trigger.to_state.attributes.lamp_entity_id, 'off') }}
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_entity_id }}"
    - service: input_boolean.turn_on
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_off_entity_id }}"

- alias: Door closed for 30s, turn off lamp
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backdoor_contact
        - binary_sensor.frontdoor_contact
      to: "off"
      for:
        seconds: 30
  condition:
    - condition: template
      value_template: >-
        {{ is_state(trigger.to_state.attributes.lamp_off_entity_id, 'on') }}
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_off_entity_id }}"
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.to_state.attributes.lamp_entity_id }}"

- alias: Door open for 5 minutes, send notification
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backdoor_contact
        - binary_sensor.frontdoor_contact
      to: "on"
      for:
        minutes: 5
  action:
    - service: script.send_notification
      data_template:
        message: "ALERT: {{ trigger.to_state.attributes.friendly_name }} is still open!"
        channel: "Alarm"
        tag: "{{ trigger.entity_id }}"

- alias: Door closed, send notification
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backdoor_contact
        - binary_sensor.frontdoor_contact
      to: "off"
  action:
    - service: script.send_notification
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} is closed!"
        channel: "Alarm"
        tag: "{{ trigger.entity_id }}"
        allow_clear: "true"

- alias: Front Door Mailbox movement, send notification
  trigger:
    - platform: state
      entity_id: sensor.frontdoormailbox_action
      from: ""
  condition:
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != 'unknown' and trigger.to_state.state != 'unavailable' and is_state('binary_sensor.frontdoor_contact', 'off') }}
  action:
    - service: script.send_notification
      data_template:
        message: "Movement detected on Front Door Mailbox"
        channel: "Automation"
        tag: "frontdoormailbox"

- alias: Arm the alarm for night mode at 01:00
  trigger:
    - platform: time
      at: "01:00:00"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: "disarmed"
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home_alarm

- alias: Disarm the alarm from night mode at 07:00
  trigger:
    - platform: time
      at: "07:00:00"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: "armed_night"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm

- alias: Everyone not home, arm alarm for away mode
  trigger:
    - platform: state
      entity_id:
        - person.pedro
        - person.joana
      from: "home"
  condition:
    - condition: template
      value_template: >-
        {{ not(is_state('person.pedro', 'home') or is_state('person.joana', 'home')) }}
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm

- alias: Someone home, disarm alarm from away mode
  trigger:
    - platform: state
      entity_id:
        - person.pedro
        - person.joana
      to: "home"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: "armed_away"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm

- alias: Smart Vibration Sensor movement, send notification
  trigger:
    - platform: state
      entity_id: sensor.smartvibrationsensor_action
      from: ""
  condition:
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != 'unknown' and trigger.to_state.state != 'unavailable' }}
  action:
    - service: script.send_notification_with_lower_floor_camera_snapshot
      data_template:
        message: "Movement detected on Smart Vibration Sensor"

- alias: Phone battery at 90% and charging, send notification
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.joana_oneplus7_battery
        - sensor.pedro_oneplus7pro_battery
      above: 89
      below: 100
  condition:
    - condition: template
      value_template: >-
        {{ is_state(trigger.entity_id ~ '_state', 'charging') }}
  action:
    - service: script.send_notification
      data_template:
        recipient: "{{ trigger.to_state.attributes.recipient }}"
        message: "Phone battery charged to 90%!"
        channel: "Phone"
        tag: "Battery"

- alias: Phone battery fully charged, send notification
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.joana_oneplus7_battery
        - sensor.pedro_oneplus7pro_battery
      above: 99
  action:
    - service: script.send_notification
      data_template:
        recipient: "{{ trigger.to_state.attributes.recipient }}"
        message: "Phone battery fully charged!"
        channel: "Phone"
        tag: "Battery"

- alias: Phone not charging, clear notification
  trigger:
    - platform: state
      entity_id:
        - sensor.joana_oneplus7_battery_state
        - sensor.pedro_oneplus7pro_battery_state
      to: "discharging"
  action:
    - service: script.clear_notification
      data_template:
        recipient: "{{ trigger.to_state.attributes.recipient }}"
        channel: "Phone"
        tag: "Battery"

- alias: Update available, send notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: script.send_notification
      data_template:
        recipient: "pedro"
        message: "Home Assistant update available!"
        channel: "System"
        tag: "homeassistantupdate"

- alias: Zigbee2mqtt Log Level
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
        topic: "zigbee2mqtt/bridge/config/log_level"
