#- platform: workday
#  country: UK

- platform: mqtt
  name: Back Door State
  device_class: door
  state_topic: "zigbee2mqtt/BackDoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: >-
    {{ value_json.contact }}

- platform: mqtt
  name: Front Door State
  device_class: door
  state_topic: "zigbee2mqtt/FrontDoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: >-
    {{ value_json.contact }}

- platform: ping
  name: UniFi Cloud Key Gen2 Plus
  host: !secret unifi_cloud_key_host

- platform: ping
  name: Philips Hue Bridge 2.1
  host: !secret philips_hue_bridge_host

- platform: ping
  name: Synology DS412+ NAS
  host: !secret synology_ds412plus_nas_host

- platform: ping
  name: Raspberry Pi 2 Model B
  host: !secret raspberry_pi_2_model_b_host

- platform: template
  sensors:

    lg_smart_tv_is_watching_live_tv:
      friendly_name: Live TV
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') }}

    lg_smart_tv_is_watching_prime_video:
      friendly_name: Prime Video
      icon_template: mdi:amazon
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Amazon Prime Video') }}

    lg_smart_tv_is_watching_xbox_one_x:
      friendly_name: Xbox One X
      icon_template: mdi:xbox
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Xbox One X') }}

    lg_smart_tv_is_watching_netflix:
      friendly_name: Netflix
      icon_template: mdi:netflix
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Netflix') }}

    lg_smart_tv_is_watching_plex:
      friendly_name: Plex
      icon_template: mdi:plex
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Plex') }}

    lg_smart_tv_is_watching_youtube:
      friendly_name: YouTube
      icon_template: mdi:youtube
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'YouTube') }}

    lg_smart_tv_is_watching_bbc_iplayer:
      friendly_name: BBC iPlayer
      icon_template: mdi:television-guide
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'BBC iPlayer') }}

    lg_smart_tv_is_watching_all_4:
      friendly_name: All 4
      entity_id: media_player.lg_smart_tv
      icon_template: mdi:television-guide
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'All 4') }}

    lg_smart_tv_is_watching_bbc_one:
      friendly_name: BBC ONE
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and is_state_attr('media_player.lg_smart_tv', 'media_title', 'BBC ONE Lon') }}

    lg_smart_tv_is_watching_bbc_one_hd:
      friendly_name: BBC ONE HD
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and is_state_attr('media_player.lg_smart_tv', 'media_title', 'BBC ONE HD') }}

    lg_smart_tv_is_watching_channel_4:
      friendly_name: Channel 4
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and is_state_attr('media_player.lg_smart_tv', 'media_title', 'Channel 4') }}

    lg_smart_tv_is_watching_channel_4_hd:
      friendly_name: Channel 4 HD
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and is_state_attr('media_player.lg_smart_tv', 'media_title', 'Channel 4 HD') }}

    lg_smart_tv_is_watching_bbc_news:
      friendly_name: BBC NEWS
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and is_state_attr('media_player.lg_smart_tv', 'media_title', 'BBC NEWS') }}

    lg_smart_tv_is_watching_bbc_news_hd:
      friendly_name: BBC NEWS HD
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and is_state_attr('media_player.lg_smart_tv', 'media_title', 'BBC NEWS HD') }}

    lg_smart_tv_is_watching_sky_news:
      friendly_name: Sky News
      icon_template: mdi:television-classic
      entity_id: media_player.lg_smart_tv
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'source', 'Live TV') and is_state_attr('media_player.lg_smart_tv', 'media_title', 'Sky News') }}
