homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  currency: GBP
  time_zone: Europe/London
  country: GB
  internal_url: !secret internal_url

  customize: !include customize.yaml

  customize_glob: !include customize_glob.yaml

  packages:
    integrations: !include_dir_named integrations/

automation: !include automations.yaml
