homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London
  internal_url: !secret internal_url
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

#default_config:

frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

updater:
  reporting: false

config:

ssdp:

zeroconf:
  default_interface: true
  ipv6: false

discovery:

sun:

system_health:

api:

stream:

wake_on_lan:

mobile_app:

zigbee2mqtt_networkmap:

mqtt:
  broker: !secret mqtt_broker
  discovery: true
#  username: !secret mqtt_username
#  password: !secret mqtt_password

ifttt:
  key: !secret ifttt_key

weather:
#  - platform: metoffice
#    api_key: !secret metoffice_api_key
  - platform: darksky
    api_key: !secret darksky_api_key

recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml
person: !include persons.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
#media_player: !include media_players.yaml
#group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
notify: !include notify.yaml
#lock: !include locks.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
#timer: !include timers.yaml
camera: !include cameras.yaml
alexa: !include alexa.yaml
rest_command: !include rest_command.yaml
influxdb: !include influxdb.yaml
webostv: !include webostv.yaml
alarm_control_panel: !include alarm_control_panel.yaml
light: !include light.yaml
panel_iframe: !include panel_iframe.yaml
