homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

#default_config:

frontend:
  themes: !include themes.yaml
  javascript_version: latest

lovelace:
  mode: yaml

updater:

config:

#discovery:

#conversation:

#map:

sun:

system_health:

#tts:
#  - platform: google

#cloud:

webhook:

zigbee2mqtt_networkmap:

panel_iframe:
  networkmap:
    title: Zigbee Map
    url: "/local/zigbee2mqtt_networkmap/map.html"
    icon: mdi:graphql

mqtt:
  broker: !secret mqtt_broker
#  username: !secret mqtt_username
#  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

ifttt:
  key: !secret ifttt_key

weather:
#  - platform: metoffice
#    api_key: !secret metoffice_api_key
  - platform: darksky
    api_key: !secret darksky_api_key

recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml
person: !include persons.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_trackers.yaml
media_player: !include media_players.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
notify: !include notify.yaml
#lock: !include locks.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
#timer: !include timers.yaml
camera: !include cameras.yaml
