person.pedro:
  entity_picture: /local/pedro.jpg

person.joana:
  entity_picture: /local/joana.jpg

binary_sensor.back_door_state:
  friendly_name: Back Door
  lamp_entity_id: light.lamp_3
  lamp_off_entity_id: input_boolean.turn_off_lamp_on_back_door_close
  send_notification_entity_id: input_boolean.send_notification_on_back_door_close

binary_sensor.front_door_state:
  friendly_name: Front Door
  lamp_entity_id: light.lamp_2
  lamp_off_entity_id: input_boolean.turn_off_lamp_on_front_door_close
  send_notification_entity_id: input_boolean.send_notification_on_front_door_close

binary_sensor.philips_hue_bridge:
  icon: mdi:server

binary_sensor.synology_ds412_nas:
  icon: mdi:nas

binary_sensor.raspberry_pi_2_model_b:
  icon: mdi:raspberry-pi

sensor.bakerloo:
  friendly_name: Bakerloo Line
  icon: mdi:subway-variant

sensor.london_overground:
  friendly_name: Overground
  icon: mdi:train

sensor.victoria:
  friendly_name: Victoria Line
  icon: mdi:subway-variant

sensor.islington:
  friendly_name: Islington polution
