person.pedro:
  entity_picture: /local/pedro.jpg

person.joana:
  entity_picture: /local/joana.jpg

device_tracker.pedro_oneplus7pro:
  friendly_name: Pedro OnePlus 7 Pro GPS
  icon: mdi:cellphone-android

device_tracker.joana_oneplus7:
  friendly_name: Joana OnePlus 7 GPS
  icon: mdi:cellphone-android

device_tracker.oneplus_7_pro_pedro:
  friendly_name: Pedro OnePlus 7 Pro WiFi
  icon: mdi:cellphone-android

device_tracker.oneplus_7_joana:
  friendly_name: Joana OnePlus 7 WiFi
  icon: mdi:cellphone-android

binary_sensor.backdoor_contact:
  friendly_name: Back Door
  lamp_entity_id: light.lamp_3
  lamp_off_entity_id: input_boolean.turn_off_lamp_on_back_door_close
  send_notification_entity_id: input_boolean.send_notification_on_back_door_close

binary_sensor.frontdoor_contact:
  friendly_name: Front Door
  lamp_entity_id: light.lamp_2
  lamp_off_entity_id: input_boolean.turn_off_lamp_on_front_door_close
  send_notification_entity_id: input_boolean.send_notification_on_front_door_close

binary_sensor.philips_hue_bridge:
  icon: mdi:server

binary_sensor.synology_ds412_nas:
  icon: mdi:nas

binary_sensor.raspberry_pi_2_model_b:
  icon: mdi:raspberry-pi

sensor.bakerloo:
  friendly_name: Bakerloo Line
  icon: mdi:subway-variant

sensor.london_overground:
  friendly_name: Overground
  icon: mdi:train

sensor.victoria:
  friendly_name: Victoria Line
  icon: mdi:subway-variant

sensor.islington:
  friendly_name: Air Polution

sensor.external_ip:
  icon: mdi:wan

sensor.reported_ip:
  icon: mdi:wan

switch.smartplug1_switch:
  friendly_name: Living Room Smart Plug

switch.smartplug2_switch:
  friendly_name: Lower Floor Smart Plug

switch.smartplug3_switch:
  friendly_name: Smart Plug 3

switch.smartplug4_switch:
  friendly_name: Kids Bedroom Smart Plug

switch.smartplug5_switch:
  friendly_name: Washing Machine Smart Plug
