person.pedro:
  entity_picture: /local/pedro.jpg

person.joana:
  entity_picture: /local/joana.jpg

device_tracker.pedro_oneplus7pro:
  friendly_name: Pedro OnePlus 7 Pro GPS
  icon: mdi:cellphone-android

device_tracker.joana_oneplus7:
  friendly_name: Joana OnePlus 7 GPS
  icon: mdi:cellphone-android

device_tracker.oneplus_7_pro_pedro:
  friendly_name: Pedro OnePlus 7 Pro WiFi
  icon: mdi:cellphone-android

device_tracker.oneplus_7_joana:
  friendly_name: Joana OnePlus 7 WiFi
  icon: mdi:cellphone-android

binary_sensor.back_door_contact:
  friendly_name: Back Door
  lamp_entity_id: light.lamp_3
  lamp_off_entity_id: input_boolean.turn_off_lamp_on_back_door_close

binary_sensor.front_door_contact:
  friendly_name: Front Door
  lamp_entity_id: light.lamp_2
  lamp_off_entity_id: input_boolean.turn_off_lamp_on_front_door_close

binary_sensor.master_bedroom_pir_sensor_occupancy:
  friendly_name: Master Bedroom occupancy

binary_sensor.philips_hue_bridge:
  icon: mdi:server

binary_sensor.synology_ds412_nas:
  icon: mdi:nas

binary_sensor.raspberry_pi_2_model_b:
  icon: mdi:raspberry-pi

light.kids_bedroom_dimmer:
  friendly_name: Kids Bedroom Dimmer

light.lamp_4:
  friendly_name: Lamp 4

light.lamp_5:
  friendly_name: Lamp 5

light.lamp_6:
  friendly_name: Lamp 6

light.master_bedroom_dimmer:
  friendly_name: Master Bedroom Dimmer

sensor.bakerloo:
  friendly_name: Bakerloo Line
  icon: mdi:subway-variant

sensor.london_overground:
  friendly_name: Overground
  icon: mdi:train

sensor.victoria:
  friendly_name: Victoria Line
  icon: mdi:subway-variant

sensor.islington:
  friendly_name: Air Polution

sensor.external_ip:
  icon: mdi:wan

sensor.pedro_oneplus7pro_battery_level:
  recipient: pedro

sensor.pedro_oneplus7pro_battery_state:
  recipient: pedro

sensor.joana_oneplus7_battery_level:
  recipient: joana

sensor.joana_oneplus7_battery_state:
  recipient: joana

sensor.reported_ip:
  icon: mdi:wan

sensor.kids_bedroom_climate_temperature:
  friendly_name: Kids Bedroom Temperature

sensor.kids_bedroom_climate_humidity:
  friendly_name: Kids Bedroom Humidity

sensor.living_room_climate_temperature:
  friendly_name: Living Room Temperature

sensor.living_room_climate_humidity:
  friendly_name: Living Room Humidity

sensor.lower_floor_climate_temperature:
  friendly_name: Lower Floor Temperature

sensor.lower_floor_climate_humidity:
  friendly_name: Lower Floor Humidity

sensor.master_bedroom_climate_temperature:
  friendly_name: Master Bedroom Temperature

sensor.master_bedroom_climate_humidity:
  friendly_name: Master Bedroom Humidity

sensor.kids_bedroom_smart_plug_power:
  switch: switch.kids_bedroom_smart_plug

sensor.master_bedroom_smart_plug_power:
  switch: switch.master_bedroom_smart_plug

switch.living_room_smart_plug:
  friendly_name: Living Room Smart Plug

switch.lower_floor_smart_plug:
  friendly_name: Lower Floor Smart Plug

switch.kids_bedroom_smart_plug:
  friendly_name: Kids Bedroom Smart Plug

switch.washing_machine_smart_plug:
  friendly_name: Washing Machine Smart Plug

switch.master_bedroom_smart_plug:
  friendly_name: Master Bedroom Smart Plug
