person.pedro:
  entity_picture: /local/pedro.jpg

person.joana:
  entity_picture: /local/joana.jpg

device_tracker.pedro_oneplus7pro:
  friendly_name: Pedro OnePlus 7 Pro GPS
  icon: mdi:cellphone-android

device_tracker.joana_oneplus7:
  friendly_name: Joana OnePlus 7 GPS
  icon: mdi:cellphone-android

device_tracker.oneplus_7_pro_pedro:
  friendly_name: Pedro OnePlus 7 Pro WiFi
  icon: mdi:cellphone-android

device_tracker.oneplus_7_joana:
  friendly_name: Joana OnePlus 7 WiFi
  icon: mdi:cellphone-android

binary_sensor.back_door_contact:
  friendly_name: Back Door

binary_sensor.front_door_contact:
  friendly_name: Front Door

binary_sensor.master_bedroom_pir_sensor_occupancy:
  friendly_name: Master Bedroom occupancy

binary_sensor.philips_hue_bridge:
  icon: mdi:server

binary_sensor.synology_ds412_nas:
  icon: mdi:nas

binary_sensor.raspberry_pi_2_model_b:
  icon: mdi:raspberry-pi

sensor.bakerloo:
  friendly_name: Bakerloo Line
  icon: mdi:subway-variant

sensor.london_overground:
  friendly_name: Overground
  icon: mdi:train

sensor.victoria:
  friendly_name: Victoria Line
  icon: mdi:subway-variant

sensor.islington:
  friendly_name: Air Polution

sensor.external_ip:
  icon: mdi:wan

sensor.reported_ip:
  icon: mdi:wan
