person.pedro:
  entity_picture: /local/pedro.jpg

person.joana:
  entity_picture: /local/joana.jpg

binary_sensor.back_door_state:
  friendly_name: Back Door

binary_sensor.front_door_state:
  friendly_name: Front Door

binary_sensor.philips_hue_bridge:
  icon: mdi:server

binary_sensor.synology_ds412_nas:
  icon: mdi:nas

binary_sensor.raspberry_pi_2_model_b:
  icon: mdi:raspberry-pi

binary_sensor.amazon_fire_tv_cube:
  icon: mdi:set-top-box

sensor.bakerloo:
  friendly_name: Bakerloo Line
  icon: mdi:subway-variant

sensor.london_overground:
  friendly_name: Overground
  icon: mdi:train

sensor.victoria:
  friendly_name: Victoria Line
  icon: mdi:subway-variant

sensor.islington:
  friendly_name: Islington polution
