living_room:
  name: Living Room
  control: hidden
  entities:
    - binary_sensor.backdoor_contact
    - binary_sensor.frontdoor_contact
    - light.living_room
    - light.lamp_1
    - light.lamp_2
    - light.lamp_3
    - media_player.lg_smart_tv
    - sensor.backdoor_battery
    - sensor.backdoor_linkquality
    - sensor.frontdoor_battery
    - sensor.frontdoor_linkquality
    - sensor.frontdoormailbox_action
    - sensor.frontdoormailbox_battery
    - sensor.frontdoormailbox_linkquality
    - sensor.livingroomclimate_temperature
    - sensor.livingroomclimate_humidity
    - sensor.livingroomclimate_pressure
    - sensor.livingroomclimate_battery
    - sensor.livingroomclimate_linkquality
    - switch.smartplug1
    - sensor.smartplug1_linkquality

lower_floor:
  name: Lower Floor
  control: hidden
  entities:
    - switch.smartplug2
    - sensor.smartplug2_linkquality

master_bedroom:
  name: Master Bedroom
  control: hidden
  entities:
    - light.master_bedroom
    - sensor.masterbedroomclimate_temperature
    - sensor.masterbedroomclimate_humidity
    - sensor.masterbedroomclimate_pressure
    - sensor.masterbedroomclimate_battery
    - sensor.masterbedroomclimate_linkquality

kids_bedroom:
  name: Kids Bedroom
  control: hidden
  entities:
    - sensor.kidsbedroomclimate_temperature
    - sensor.kidsbedroomclimate_humidity
    - sensor.kidsbedroomclimate_pressure
    - sensor.kidsbedroomclimate_battery
    - sensor.kidsbedroomclimate_linkquality
