include:
  domains:
    - media_player
  entities:
    - binary_sensor.back_door_state
    - binary_sensor.front_door_state
    - binary_sensor.living_room_camera_motion
    - binary_sensor.living_room_camera_pir_alarm
    - binary_sensor.lower_floor_camera_motion
    - binary_sensor.lower_floor_camera_pir_alarm
    - light.lamp_1
    - light.lamp_2
    - light.lamp_3
    - light.lamp_4
    - person.pedro
    - person.joana
    - sensor.living_room_temperature
    - sensor.living_room_humidity
    - sensor.master_bedroom_temperature
    - sensor.master_bedroom_humidity
    - sensor.kids_bedroom_temperature
    - sensor.kids_bedroom_humidity
    - sensor.smart_vibration_sensor
    - switch.living_room_smart_plug
    - switch.lower_floor_smart_plug
