pedro_oneplus6:
  name: Pedro OnePlus 6 GPS
  hide_if_away: false
  icon: mdi:cellphone-android
  track: true

joana_oneplus6:
  name: Joana OnePlus 6 GPS
  hide_if_away: false
  icon: mdi:cellphone-android
  track: true

pedro_oneplus6_wifi:
  name: Pedro OnePlus 6 WiFi
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: !secret pedro_oneplus6_mac
  track: true

joana_oneplus6_wifi:
  name: Joana OnePlus 6 WiFi
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: !secret joana_oneplus6_mac
  track: true

pedro_dell_xps_15_9550:
  name: Dell XPS 15 9550 (Pedro)
  hide_if_away: false
  icon: mdi:laptop-windows
  mac: !secret pedro_dell_xps_15_9550_mac
  track: false

pedro_surface_go:
  name: Surface Go (Pedro)
  hide_if_away: false
  icon: mdi:tablet
  mac: !secret pedro_surface_go_mac
  track: false
