pedro_oneplus7pro_wifi:
  name: Pedro OnePlus 7 Pro WiFi
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: !secret pedro_oneplus7pro_mac
  track: true

joana_oneplus7_wifi:
  name: Joana OnePlus 7 WiFi
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: !secret joana_oneplus7_mac
  track: true

pedro_dell_xps_15_9550:
  name: Dell XPS 15 9550 (Pedro)
  hide_if_away: false
  icon: mdi:laptop-windows
  mac: !secret pedro_dell_xps_15_9550_mac
  track: false

pedro_surface_go:
  name: Surface Go (Pedro)
  hide_if_away: false
  icon: mdi:tablet
  mac: !secret pedro_surface_go_mac
  track: false
