pedro_oneplus6:
  name: Pedro
  picture: /local/pedro.jpg
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: !secret pedro_oneplus6_mac
  track: true

joana_oneplus6:
  name: Joana
  picture: /local/joana.jpg
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: !secret joana_oneplus6_mac
  track: true

dell_xps_15_9550_pedro:
  name: Dell XPS 15 9550 (Pedro)
  hide_if_away: false
  icon: mdi:laptop-windows
  mac: !secret dell_xps_15_9550_pedro_mac
  track: false
