include:
  domains:
    - device_tracker
  entities:
    - binary_sensor.back_door_state
    - binary_sensor.front_door_state
    - person.pedro
    - person.joana

exclude:
  domains:
    - automation
    - camera
    - group
    - hangouts
    - input_boolean
    - input_number
    - input_select
    - light
    - media_player
    - sensor
    - script
    - sun
    - switch
    - timer
    - updater
    - weather
    - weblink
    - zigbee2mqtt_networkmap
    - zone
