include:
  entities:
    - binary_sensor.back_door_state
    - binary_sensor.external_ip_detected
    - binary_sensor.front_door_state
    - person.pedro
    - person.joana
    - sensor.external_ip
    - sensor.reported_ip
    - sensor.front_door_mailbox
    - switch.living_room_smart_plug
    - switch.lower_floor_smart_plug
