include:
  domains:
    - device_tracker
    - media_player
  entities:
    - binary_sensor.back_door_state
    - binary_sensor.front_door_state
    - light.living_room
    - light.master_bedroom
    - person.pedro
    - person.joana
    - switch.living_room_outlet
    - switch.lower_floor_outlet

exclude:
  domains:
    - automation
    - group
    - input_boolean
    - input_select
    - sensor
    - sun
    - timer
    - updater
    - weather
    - weblink
    - zone
