include:
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.backdoor_contact
    - binary_sensor.external_ip_detected
    - binary_sensor.frontdoor_contact
    - binary_sensor.pirsensor_occupancy
    - person.joana
    - person.pedro
    - sensor.external_ip
    - sensor.reported_ip
    - switch.smartplug1_switch
    - switch.smartplug2_switch
    - switch.smartplug3_switch
    - switch.smartplug4_switch
    - switch.smartplug5_switch
    - switch.smartplug6_switch
    - switch.smartplug7_switch
