- name: pushbullet
  platform: pushbullet
  api_key: !secret pushbullet_api_key

- name: hangouts_pedro
  platform: hangouts
  default_conversations: !secret hangouts_conversations_pedro

- name: hangouts_all
  platform: hangouts
  default_conversations: !secret hangouts_conversations_all
