- id: pedro
  name: Pedro
  device_trackers:
    - device_tracker.pedro_oneplus7pro
    - device_tracker.oneplus_7_pro_pedro

- id: joana
  name: Joana
  device_trackers:
    - device_tracker.joana_oneplus7
    - device_tracker.oneplus_7_joana
