- id: pedro
  name: Pedro
  device_trackers:
    - device_tracker.gm1913
    - device_tracker.oneplus_7_pro_pedro

- id: joana
  name: Joana
  device_trackers:
    - device_tracker.gm1903
    - device_tracker.oneplus_7_joana
