purge_keep_days: 5
purge_interval: 1

include:
  domains:
    - light
    - media_player
  entities:
    - binary_sensor.backdoor_contact
    - binary_sensor.external_ip_detected
    - binary_sensor.frontdoor_contact
    - device_tracker.oneplus_7_joana
    - device_tracker.oneplus_7_pro_pedro
    - person.joana
    - person.pedro
    - sensor.cpu_temperature
    - sensor.external_ip
    - sensor.kidsbedroomclimate_humidity
    - sensor.kidsbedroomclimate_temperature
    - sensor.livingroomclimate_humidity
    - sensor.livingroomclimate_temperature
    - sensor.lowerfloorclimate_humidity
    - sensor.lowerfloorclimate_temperature
    - sensor.masterbedroomclimate_humidity
    - sensor.masterbedroomclimate_temperature
    - sensor.reported_ip
    - switch.smartplug1_switch
    - switch.smartplug2_switch
    - switch.smartplug3_switch
    - switch.smartplug4_switch
    - switch.smartplug5_switch
