purge_keep_days: 5
purge_interval: 1

include:
  domains:
    - light
    - media_player
  entities:
    - binary_sensor.back_door_state
    - binary_sensor.external_ip_detected
    - binary_sensor.front_door_state
    - binary_sensor.living_room_camera_motion
    - binary_sensor.living_room_camera_pir_alarm
    - binary_sensor.lower_floor_camera_motion
    - binary_sensor.lower_floor_camera_pir_alarm
    - device_tracker.oneplus_7_pro_pedro
    - device_tracker.oneplus_7_joana
    - person.pedro
    - person.joana
    - sensor.cpu_temperature
    - sensor.external_ip
    - sensor.reported_ip
    - sensor.front_door_mailbox
    - sensor.living_room_temperature
    - sensor.living_room_humidity
    - sensor.master_bedroom_temperature
    - sensor.master_bedroom_humidity
    - sensor.kids_bedroom_temperature
    - sensor.kids_bedroom_humidity
    - sensor.smart_vibration_sensor
    - switch.living_room_smart_plug
    - switch.lower_floor_smart_plug
