send_notification:
  sequence:
    - service: notify.pushbullet
      data_template:
        title: "Home Assistant"
        message: "{{ message }}"
#    - service: ifttt.trigger
#      data_template:
#        event: "homeassistant-notification"
#        value1: "{{ message }}"
