send_notification_pedro:
  sequence:
    - service: notify.hangouts_pedro
      data_template:
        message: "{{ message }}"
        data:
          image_file: "{{ filename }}"

send_notification_all:
  sequence:
    - service: notify.hangouts_all
      data_template:
        message: "{{ message }}"
        data:
          image_file: "{{ filename }}"

send_notification_with_living_room_camera_snapshot:
  sequence:
    - service: camera.snapshot
      data:
        entity_id: camera.living_room_camera
        filename: "/config/www/snapshot.jpg"
    - service: script.send_notification_pedro
      data_template:
        message: "{{ message }}"
        filename: "/config/www/snapshot.jpg"

send_notification_with_lower_floor_camera_snapshot:
  sequence:
    - service: camera.snapshot
      data:
        entity_id: camera.lower_floor_camera
        filename: "/config/www/snapshot2.jpg"
    - service: script.send_notification_pedro
      data_template:
        message: "{{ message }}"
        filename: "/config/www/snapshot2.jpg"

update_dynamic_dns:
  sequence:
    - service: rest_command.cloudflare_update
      data_template:
        api_token: !secret cloudflare_api_token
        zone_id: !secret cloudflare_zone_id
        dns_record_id: !secret cloudflare_dns_record_id
        dns_record_name: !secret cloudflare_dns_record_name
        ip_address: "{{ ip_address }}"

turn_on_lg_smart_tv:
  sequence:
    - condition: state
      entity_id: media_player.lg_smart_tv
      state: "off"
    - service: media_player.turn_on
      data_template:
        entity_id: media_player.lg_smart_tv

watch_netflix_on_lg_smart_tv:
  sequence:
    - service: script.turn_on_lg_smart_tv
    - wait_template: >-
        {{ not is_state("media_player.lg_smart_tv", "off") }}
      timeout:
        seconds: 15
      continue_on_timeout: "true"
    - service: media_player.select_source
      data_template:
        entity_id: media_player.lg_smart_tv
        source: "Netflix"

watch_plex_on_lg_smart_tv:
  sequence:
    - service: script.turn_on_lg_smart_tv
    - wait_template: >-
        {{ not is_state("media_player.lg_smart_tv", "off") }}
      timeout:
        seconds: 15
      continue_on_timeout: "true"
    - service: media_player.select_source
      data_template:
        entity_id: media_player.lg_smart_tv
        source: "Plex"

watch_bbc_one_on_lg_smart_tv:
  sequence:
    - service: script.turn_on_lg_smart_tv
    - wait_template: >-
        {{ not is_state("media_player.lg_smart_tv", "off") }}
      timeout:
        seconds: 15
      continue_on_timeout: "true"
    - service: media_player.play_media
      data_template:
        entity_id: media_player.lg_smart_tv
        media_content_id: "BBC ONE HD"
        media_content_type: "channel"

watch_bbc_news_on_lg_smart_tv:
  sequence:
    - service: script.turn_on_lg_smart_tv
    - wait_template: >-
        {{ not is_state("media_player.lg_smart_tv", "off") }}
      timeout:
        seconds: 15
      continue_on_timeout: "true"
    - service: media_player.play_media
      data_template:
        entity_id: media_player.lg_smart_tv
        media_content_id: "BBC NEWS HD"
        media_content_type: "channel"

watch_channel_4_on_lg_smart_tv:
  sequence:
    - service: script.turn_on_lg_smart_tv
    - wait_template: >-
        {{ not is_state("media_player.lg_smart_tv", "off") }}
      timeout:
        seconds: 15
      continue_on_timeout: "true"
    - service: media_player.play_media
      data_template:
        entity_id: media_player.lg_smart_tv
        media_content_id: "Channel 4 HD"
        media_content_type: "channel"
