#- platform: time_date
#  display_options:
#    - 'time'
#    - 'date'
#    - 'date_time'
#    - 'time_date'
#    - 'time_utc'
#    - 'beat'

- platform: worldclock
  name: Eastern Time Zone
  time_zone: EST5EDT

- platform: worldclock
  name: Pacific Time Zone
  time_zone: PST8PDT

- platform: dnsip
  name: External IP
  scan_interval: 30

- platform: dnsip
  name: Reported IP
  hostname: !secret cloudflare_dns_record_name
  resolver: 1.1.1.1
  scan_interval: 30

#- platform: metoffice
#  api_key: !secret metoffice_api_key
#  monitored_conditions:
#    - weather
#    - temperature
#    - feels_like_temperature
#    - wind_speed
#    - wind_direction
#    - wind_gust
#    - visibility
#    - visibility_distance

#- platform: google_travel_time
#  name: Pedro to Home
#  api_key: !secret google_travel_time_api_key
#  origin: device_tracker.pedro_oneplus7pro
#  destination: zone.home
#  travel_mode: transit

- platform: moon

- platform: mqtt
  name: Zigbee2mqtt Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:server-network

- platform: mqtt
  name: LivingRoomClimate Temperature
  device_class: temperature
  state_topic: "zigbee2mqtt/LivingRoomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: >-
    {{ value_json.temperature }}
- platform: mqtt
  name: LivingRoomClimate Humidity
  device_class: humidity
  state_topic: "zigbee2mqtt/LivingRoomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.humidity }}
- platform: mqtt
  name: LivingRoomClimate Pressure
  device_class: pressure
  state_topic: "zigbee2mqtt/LivingRoomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: >-
    {{ value_json.pressure }}
- platform: mqtt
  name: LivingRoomClimate Battery
  device_class: battery
  state_topic: "zigbee2mqtt/LivingRoomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: LivingRoomClimate LinkQuality
  state_topic: "zigbee2mqtt/LivingRoomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: mqtt
  name: LowerFloorClimate Temperature
  device_class: temperature
  state_topic: "zigbee2mqtt/LowerFloorClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: >-
    {{ value_json.temperature }}
- platform: mqtt
  name: LowerFloorClimate Humidity
  device_class: humidity
  state_topic: "zigbee2mqtt/LowerFloorClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.humidity }}
- platform: mqtt
  name: LowerFloorClimate Pressure
  device_class: pressure
  state_topic: "zigbee2mqtt/LowerFloorClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: >-
    {{ value_json.pressure }}
- platform: mqtt
  name: LowerFloorClimate Battery
  device_class: battery
  state_topic: "zigbee2mqtt/LowerFloorClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: LowerFloorClimate LinkQuality
  state_topic: "zigbee2mqtt/LowerFloorClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: mqtt
  name: MasterBedroomClimate Temperature
  device_class: temperature
  state_topic: "zigbee2mqtt/MasterBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: >-
    {{ value_json.temperature }}
- platform: mqtt
  name: MasterBedroomClimate Humidity
  device_class: humidity
  state_topic: "zigbee2mqtt/MasterBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.humidity }}
- platform: mqtt
  name: MasterBedroomClimate Pressure
  device_class: pressure
  state_topic: "zigbee2mqtt/MasterBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: >-
    {{ value_json.pressure }}
- platform: mqtt
  name: MasterBedroomClimate Battery
  device_class: battery
  state_topic: "zigbee2mqtt/MasterBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: MasterBedroomClimate LinkQuality
  state_topic: "zigbee2mqtt/MasterBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: mqtt
  name: KidsBedroomClimate Temperature
  device_class: temperature
  state_topic: "zigbee2mqtt/KidsBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: >-
    {{ value_json.temperature }}
- platform: mqtt
  name: KidsBedroomClimate Humidity
  device_class: humidity
  state_topic: "zigbee2mqtt/KidsBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.humidity }}
- platform: mqtt
  name: KidsBedroomClimate Pressure
  device_class: pressure
  state_topic: "zigbee2mqtt/KidsBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: >-
    {{ value_json.pressure }}
- platform: mqtt
  name: KidsBedroomClimate Battery
  device_class: battery
  state_topic: "zigbee2mqtt/KidsBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: KidsBedroomClimate LinkQuality
  state_topic: "zigbee2mqtt/KidsBedroomClimate"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: mqtt
  name: BackDoor Battery
  device_class: battery
  state_topic: "zigbee2mqtt/BackDoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: BackDoor LinkQuality
  state_topic: "zigbee2mqtt/BackDoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: mqtt
  name: FrontDoor Battery
  device_class: battery
  state_topic: "zigbee2mqtt/FrontDoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: FrontDoor LinkQuality
  state_topic: "zigbee2mqtt/FrontDoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: mqtt
  name: FrontDoorMailbox Action
  state_topic: "zigbee2mqtt/FrontDoorMailbox"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:mailbox-up
  value_template: >-
    {{ value_json.action }}
- platform: mqtt
  name: FrontDoorMailbox Battery
  device_class: "battery"
  state_topic: "zigbee2mqtt/FrontDoorMailbox"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: FrontDoorMailbox LinkQuality
  state_topic: "zigbee2mqtt/FrontDoorMailbox"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: mqtt
  name: SmartVibrationSensor Action
  state_topic: "zigbee2mqtt/SmartVibrationSensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: >-
    {{ value_json.action }}
- platform: mqtt
  name: SmartVibrationSensor Battery
  device_class: "battery"
  state_topic: "zigbee2mqtt/SmartVibrationSensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: mqtt
  name: SmartVibrationSensor LinkQuality
  state_topic: "zigbee2mqtt/SmartVibrationSensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: "mqtt"
  name: SmartSwitch Click
  state_topic: "zigbee2mqtt/SmartSwitch"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:toggle-switch
  value_template: >-
    {{ value_json.click }}
- platform: "mqtt"
  name: SmartSwitch Battery
  device_class: "battery"
  state_topic: "zigbee2mqtt/SmartSwitch"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: >-
    {{ value_json.battery }}
- platform: "mqtt"
  name: SmartSwitch LinkQuality
  state_topic: "zigbee2mqtt/SmartSwitch"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: "mqtt"
  name: SmartPlug1 LinkQuality
  state_topic: "zigbee2mqtt/SmartPlug1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: "mqtt"
  name: SmartPlug2 LinkQuality
  state_topic: "zigbee2mqtt/SmartPlug2"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}

- platform: "mqtt"
  name: SmartPlug3 LinkQuality
  state_topic: "zigbee2mqtt/SmartPlug3"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: >-
    {{ value_json.linkquality }}
- platform: "mqtt"
  name: SmartPlug3 Power
  device_class: "power"
  state_topic: "zigbee2mqtt/SmartPlug3"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "W"
  value_template: >-
    {{ value_json.power }}

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  scan_interval: 150
  unit_of_measurement: "째C"
  value_template: >-
    {{ value | multiply(0.001) | round(2) }}

- platform: london_underground
  line:
    - Bakerloo
    - London Overground
    - Victoria

- platform: london_air
  locations:
    - Islington

- platform: template
  sensors:

    lg_smart_tv_is_playing:
      entity_id: media_player.lg_smart_tv
      value_template: 0
      icon_template: >-
        {% if is_state('media_player.lg_smart_tv', 'playing') %}mdi:pause{% else %}mdi:play{% endif %}

    pedro_oneplus7pro_battery:
      unit_of_measurement: "%"
      device_class: battery
      value_template: >-
        {{ state_attr('device_tracker.pedro_oneplus7pro', 'battery_level') }}

    joana_oneplus7_battery:
      unit_of_measurement: "%"
      device_class: battery
      value_template: >-
        {{ state_attr('device_tracker.joana_oneplus7', 'battery_level') }}
