#- platform: time_date
#  display_options:
#    - 'time'
#    - 'date'
#    - 'date_time'
#    - 'time_date'
#    - 'time_utc'
#    - 'beat'

- platform: worldclock
  name: Eastern Time Zone
  time_zone: EST5EDT

- platform: worldclock
  name: Pacific Time Zone
  time_zone: PST8PDT

- platform: dnsip
  name: External IP
  scan_interval: 30

- platform: dnsip
  name: Reported IP
  hostname: !secret cloudflare_dns_record_name
  resolver: 1.1.1.1
  scan_interval: 30

#- platform: metoffice
#  api_key: !secret metoffice_api_key
#  monitored_conditions:
#    - weather
#    - temperature
#    - feels_like_temperature
#    - wind_speed
#    - wind_direction
#    - wind_gust
#    - visibility
#    - visibility_distance

#- platform: google_travel_time
#  name: Pedro to Home
#  api_key: !secret google_travel_time_api_key
#  origin: device_tracker.gm1913
#  destination: zone.home
#  travel_mode: transit

- platform: moon

- platform: mqtt
  name: Zigbee2mqtt Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:server-network

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  scan_interval: 150
  unit_of_measurement: "°C"
  value_template: >-
    {{ value | multiply(0.001) | round(2) }}

- platform: london_underground
  line:
    - Bakerloo
    - London Overground
    - Victoria

- platform: london_air
  locations:
    - Islington

- platform: mold_indicator
  name: Living Room Mold
  indoor_temp_sensor: sensor.livingroomclimate_temperature
  indoor_humidity_sensor: sensor.livingroomclimate_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 2

- platform: mold_indicator
  name: Master Bedroom Mold
  indoor_temp_sensor: sensor.masterbedroomclimate_temperature
  indoor_humidity_sensor: sensor.masterbedroomclimate_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 2

- platform: mold_indicator
  name: Kids Bedroom Mold
  indoor_temp_sensor: sensor.kidsbedroomclimate_temperature
  indoor_humidity_sensor: sensor.kidsbedroomclimate_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 2

- platform: template
  sensors:

    lg_smart_tv_is_playing:
      entity_id: media_player.lg_smart_tv
      value_template: 0
      icon_template: >-
        {% if is_state('media_player.lg_smart_tv', 'playing') %}mdi:pause{% else %}mdi:play{% endif %}

    outside_temperature:
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: >-
        {{ state_attr('weather.dark_sky', 'temperature') }}
