- platform: mqtt
  name: SmartPlug1 Switch
  state_topic: "zigbee2mqtt/SmartPlug1"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  command_topic: "zigbee2mqtt/SmartPlug1/set"
  value_template: >-
    {{ value_json.state }}

- platform: mqtt
  name: SmartPlug2 Switch
  state_topic: "zigbee2mqtt/SmartPlug2"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  command_topic: "zigbee2mqtt/SmartPlug2/set"
  value_template: >-
    {{ value_json.state }}

- platform: mqtt
  name: SmartPlug3 Switch
  state_topic: "zigbee2mqtt/SmartPlug3"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  command_topic: "zigbee2mqtt/SmartPlug3/set"
  value_template: >-
    {{ value_json.state }}

- platform: template
  switches:
    lg_smart_tv_volume_mute:
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'is_volume_muted', true) }}
      turn_on:
        service: media_player.volume_mute
        data:
          entity_id: media_player.lg_smart_tv
          is_volume_muted: true
      turn_off:
        service: media_player.volume_mute
        data:
          entity_id: media_player.lg_smart_tv
          is_volume_muted: false
