- platform: mqtt
  name: Living Room Outlet
  state_topic: "zigbee2mqtt/LivingRoomOutlet"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  command_topic: "zigbee2mqtt/LivingRoomOutlet/set"
  value_template: >-
    {{ value_json.state }}

- platform: mqtt
  name: Lower Floor Outlet
  state_topic: "zigbee2mqtt/LowerFloorOutlet"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  command_topic: "zigbee2mqtt/LowerFloorOutlet/set"
  value_template: >-
    {{ value_json.state }}

- platform: template
  switches:
    lg_smart_tv_volume_mute:
      value_template: >-
        {{ is_state_attr('media_player.lg_smart_tv', 'is_volume_muted', true) }}
      turn_on:
        service: media_player.volume_mute
        data:
          entity_id: media_player.lg_smart_tv
          is_volume_muted: true
      turn_off:
        service: media_player.volume_mute
        data:
          entity_id: media_player.lg_smart_tv
          is_volume_muted: false