title: Home
resources:
#  - url: /local/card-tools.js?v=1
#    type: js
  - url: /local/vertical-stack-in-card.js?v=0.0.9
    type: js
  - url: /local/button-entity-row.js
    type: js
  - url: /local/button-cards.js?track=true
    type: module
views:
  - !include lovelace/main.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/ambient.yaml
  - !include lovelace/media.yaml
  - !include lovelace/people.yaml
  - !include lovelace/map.yaml
