title: Home
views:
  - !include lovelace/main.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/climate.yaml
  - !include lovelace/media.yaml
  - !include lovelace/plugs.yaml
  - !include lovelace/plants.yaml
  - !include lovelace/3dprinter.yaml
  - !include lovelace/map.yaml
