name: Home Assistant (Beta)
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  build:
    name: Test configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check configuration with Home Assistant
        uses: frenck/action-home-assistant@v1.4
        with:
          path: "./config"
          secrets: "./secrets.template.yaml"
          version: "beta"
