name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install homeassistant
    - name: Create secrets.yaml file
      run: |
        mv ./config/secrets.template.yaml ./config/secrets.yaml
    - name: Check configuration with Home Assistant
      run: |
        hass -c ./config --script check_config
